- cluster/hosts.go
- hosts/dialer.go
https://github.com/rancher/rke/issues/18
> Fix encrypted key issue

- cluster/cluster.go
- cluster/state.go
- cmd/cluster.go
- docker/docker.go
- hosts/hosts.go
- main.go
- pki/kubeconfig.go
- pki/pki.go
- services/proxy.go
* Add/Remove Handler for Control plane hosts
* Add/Remove Handler for Worker hosts
* Rebuilding Local Admin config
* Rolling update for Nginx proxy config on worker nodes
> Add/Remove Cluster plane and Worker hosts

- cluster/down.go
- cmd/cluster.go
- docker/docker.go
- hosts/hosts.go
- services/controlplane.go
- services/etcd.go
- services/kubeapi.go
- services/kubecontroller.go
- services/kubelet.go
- services/kubeproxy.go
- services/proxy.go
- services/scheduler.go
- services/workerplane.go
* Remove services' docker containers
* Clean up static mounted directories [/etc/kubernetes/ssl, /etc/cni, /opt/cni, /var/lib/etcd]
> Cluster Down/Remove

- cluster/certificates.go
- cluster/cluster.go
- cluster/state.go
- cluster/validation.go
- hosts/hosts.go
- k8s/node.go
- pki/pki.go
https://github.com/rancher/rke/issues/27
https://github.com/rancher/rke/issues/24
> Add cluster validation and regenerate kubeapi cert

- cluster/hosts.go
- vendor.conf
- vendor/github.com/rancher/types/apis/cluster.cattle.io/v1/types.go
https://github.com/rancher/rke/issues/21
> Add ssh private key path

- cmd/cluster.go
https://github.com/rancher/rke/issues/26
> Check if the cluster state is empty before upgrade

- cluster/cluster.go
- hosts/dialer.go
- hosts/hosts.go
> Clean host after removal

- cluster/hosts.go
- cluster/upgrade.go
- cmd/cluster.go
https://github.com/rancher/rke/issues/44
https://github.com/rancher/rke/issues/45
> Add error messages for adding/removing nodes while upgrade

- cluster/certificates.go
- pki/pki.go
https://github.com/rancher/rke/issues/37
> Generate new KubeAPI certificate for new nodes using the same key

- cluster/state.go
- services/proxy.go
https://github.com/rancher/rke/issues/61
> Fix rolling update bug for multi master Nginx

- addons/kubedns.go
https://github.com/rancher/rke/issues/68
> add kube-dns auto-scalling

- cluster/remove.go
- pki/deploy.go
https://github.com/rancher/rke/issues/51
> remove kubeconfig as part of cluster remove

- pki/deploy.go
Fixes https://github.com/rancher/rke/issues/79
> Remove invalid RestartPolicy

- services/kubelet.go
- services/workerplane.go
https://github.com/rancher/rke/issues/69
> Add multiple role labels to nodes

- cluster/hosts.go
https://github.com/rancher/rke/issues/73
> Fix tilde issue in ssh key path

- pki/deploy.go
Apparently missed this, another good reason to hook up Drone
> fix go fmt after removing RestartPolicy

- cluster/cluster.go
- cluster/hosts.go
- cluster/reconcile.go
- cluster/remove.go
- cluster/state.go
- cmd/up.go
- docker/docker.go
- hosts/hosts.go
- pki/deploy.go
- pki/pki.go
- pki/pki_test.go
- services/controlplane.go
- services/etcd.go
- services/kubeapi.go
- services/kubecontroller.go
- services/kubelet.go
- services/kubeproxy.go
- services/proxy.go
- services/scheduler.go
- services/workerplane.go
Regactoring Reconciliation
Add role based add/delete for services
#72 #66
> Refactor reconciliation

- pki/deploy.go
> Add information about saving local kubeconfig

- cluster/hosts.go
- cluster/validation.go
- docker/docker.go
- hosts/dialer.go
> Add host connectivity and Docker version check

- hosts/dialer.go
> Fix redundant ssh tunnels for hosts

- cluster/cluster.go
- cluster/defaults.go
- docker/docker.go
- package/service-sidekick/Dockerfile
- package/service-sidekick/build-and-push.sh
- package/service-sidekick/entrypoint.sh
- pki/deploy.go
- services/controlplane.go
- services/kubeapi.go
- services/kubecontroller.go
- services/kubelet.go
- services/kubeproxy.go
- services/scheduler.go
- services/services.go
- services/workerplane.go
> Add services sidekick container

- cluster/remove.go
- pki/deploy.go
> Add replace fatal with warning when can't remove local kubeconfig

- cluster/network.go
- network/flannel.go
- network/network.go
Added `flannel_iface` option to flannel network deployment:
```
network:
plugin: flannel
options:
flannel_iface: "ens4"
```
#134
> Add iface option to flannel

- cluster.yml
- cluster/defaults.go
- cluster/network.go
- network/calico.go
- network/network.go
https://github.com/rancher/rke/issues/115
> Enable AWS specific configuration for Calico

- cluster/certificates.go
- cluster/state.go
- cmd/config.go
- docker/docker.go
- services/kubelet_test.go
- services/kubeproxy_test.go
- services/proxy_test.go
- services/scheduler_test.go
fixed rke misspelled common words.
> update misspelled common words

- docker/docker.go
- pki/constants.go
- pki/deploy.go
- services/services.go
https://github.com/rancher/rke/issues/137
> Check image locally before pull

- addons/addons.go
- authz/authz.go
- authz/manifests.go
- cluster.yml
- cluster/cluster.go
- cluster/defaults.go
- cluster/network.go
- cmd/config.go
- k8s/clusterrole.go
- k8s/serviceaccount.go
- network/calico.go
- network/canal.go
- network/flannel.go
- network/network.go
- network/weave.go
- pki/constants.go
- services/controlplane.go
- services/kubeapi.go
- services/kubeapi_test.go
- services/kubecontroller.go
- services/kubecontroller_test.go
- services/services.go
- vendor.conf
https://github.com/rancher/rke/issues/131
> Enable RBAC

- cluster/cluster.go
- cluster/hosts.go
- cluster/reconcile.go
- cluster/state.go
- cmd/remove.go
- cmd/up.go
- hosts/dialer.go
- hosts/hosts.go
- services/controlplane.go
- services/healthcheck.go
- services/kubeapi.go
- services/kubecontroller.go
- services/kubelet.go
- services/kubeproxy.go
- services/scheduler.go
- services/services.go
- services/workerplane.go
https://github.com/rancher/rke/issues/152
> Add healthcheck for services components

- cmd/config.go
> Minor fixes

- cluster/cluster.go
- cmd/up.go
https://github.com/rancher/rke/issues/182
> Save certificates/state after deploying control plane

- services/workerplane.go
https://github.com/rancher/rke/issues/176
> Add concurrency to worker deployments

- services/healthcheck.go
> Increase healthcheck timeout to 50 seconds per service

- hosts/dialer.go
- hosts/hosts.go
- hosts/tunnel.go
> Fix regression with passphrased keys

- cluster.yml
- cluster/certificates.go
- cluster/defaults.go
- docker/docker.go
- hosts/hosts.go
- package/certs-deployer/build-and-push.sh
- package/certs-deployer/entrypoint.sh
- pki/constants.go
- pki/deploy.go
- pki/pki.go
* Requires building `rancher/rke-cert-deployer:0.1.1`
> Recoverable provisioning

- README.md
- cluster.yml
- templates/calico.go
https://github.com/rancher/rke/issues/200
> Support for Calico on GCE

- templates/calico.go
https://github.com/rancher/rke/issues/240
> Default DefaultNetworkCloudProvider is none

- cluster/network.go
- cmd/up.go
https://github.com/rancher/rancher/issues/10937
> Fix port-check update issue

- cluster/cluster.go
- cluster/hosts.go
- cluster/reconcile.go
- cluster/remove.go
- hosts/hosts.go
- k8s/node.go
- services/etcd.go
- services/kubelet.go
- services/kubelet_test.go
- services/workerplane.go
- templates/calico.go
- templates/canal.go
- templates/flannel.go
https://github.com/rancher/rancher/issues/10894
> Add unschedulable kubelet on etcd nodes

- pki/deploy.go
https://github.com/rancher/rke/issues/247
> Fix backup cert issue on docker version > 17.06

- templates/flannel.go
https://github.com/rancher/rancher/issues/11015
https://github.com/rancher/rancher/issues/10894
> fix templates in flannel

- cluster.yml
- cluster/defaults.go
- cluster/network.go
Fixes: https://github.com/rancher/rke/issues/248
Requires rke-nginx-proxy:v0.1.1 https://github.com/rancher/rke-nginx-proxy/pull/2
> Fix multi-role port-check conflict

- docker/docker.go
We run a lot of containers now, which generates a ton of low level logging, this is best moved to debug at this point.
> Change some low level logging from info to debug

- cluster/reconcile.go
- services/kubeapi.go
https://github.com/rancher/rancher/issues/11040
https://github.com/rancher/rancher/issues/10997
> Remove deleted etcd member from k8s and update kube-api with new list of members

- README.md
I was checking out rke for the first time and couldn't figure out how I was supposed to use this until I got to the blog post buried in the more details.
* Moved blog post link to Getting Started
* Minor formatting to pass [markdownlint](https://github.com/DavidAnson/markdownlint)
> Move blog post to Getting Started section. Pass lint

- cluster.yml
- cluster/certificates.go
- cluster/cluster.go
- cluster/hosts.go
- cluster/network.go
- cluster/reconcile.go
- cluster/remove.go
- docker/docker.go
- hosts/hosts.go
- pki/deploy.go
- services/controlplane.go
- services/etcd.go
- services/kubeapi.go
- services/kubecontroller.go
- services/kubelet.go
- services/kubeproxy.go
- services/proxy.go
- services/scheduler.go
- services/services.go
- services/workerplane.go
https://github.com/rancher/rke/issues/84
> Private registry authentication

- cluster.yml
- cluster/cluster.go
https://github.com/rancher/rke/issues/274
> Use cluster level k8s version

- cluster/reconcile.go
- docker/docker.go
> Fix rolling update of nginx-proxy for worker and etcd

- cluster/cluster.go
- cmd/up.go
https://github.com/rancher/rke/issues/261
> Pre-pull k8s images

- services/controlplane.go
https://github.com/rancher/rke/issues/261
> Deploy control plane in parallel

- cluster/hosts.go
- pki/deploy.go
No. 2 in https://github.com/rancher/rke/issues/261
> Refactor certificates deployment

- cluster/certificates.go
- k8s/secret.go
https://github.com/rancher/rke/issues/293
https://github.com/rancher/rke/issues/261
> Refactor saving secrets

- templates/calico.go
https://github.com/rancher/rke/issues/304
> Update calico template to use etcd tls with aws

- cluster.yml
> Revert back to ignore_docker_version in cluster.yml

- cluster.yml
- cluster/defaults.go
https://github.com/rancher/rke/issues/325
> Kubernetes default version: v1.8.7-rancher1-1

- docker/docker.go
> Add registry auth for private registries as well

- cluster/plan.go
- hosts/hosts.go
> add /var/lib/cni to kubelet mounts

- cluster/plan.go
- hosts/hosts.go
- hosts/tunnel.go
https://github.com/rancher/rke/issues/226
> Use configured docker daemon root dir on kubelet

- hosts/hosts.go
> Fix rke remove with etcd dir

- cluster/cluster.go
- cluster/hosts.go
- cluster/reconcile.go
- cluster/validation.go
- hosts/hosts.go
https://github.com/rancher/rancher/issues/11529
> Ignore inactive hosts

- cluster.yml
- cluster/defaults.go
- cmd/config.go
- hosts/dialer.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
https://github.com/rancher/rke/issues/100
Depends on https://github.com/rancher/types/pull/130
> SSH port is configurable

- cluster/validation.go
https://github.com/rancher/rancher/issues/11113
> Validate Duplicate nodes

- cluster/plan.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/authz_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/pipeline_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go
https://github.com/rancher/types/pull/246
> Use named processes map

- cluster/defaults.go
- cluster/local.go
- cmd/config.go
https://github.com/rancher/rke/issues/369
https://github.com/rancher/rancher/issues/11363
> Use default images from types

- cluster/plan.go
https://github.com/rancher/rke/issues/380
> Fix etcd process regression

- templates/kubedns.go
this adds a service account and appropriate cluster role binding
for the kubedns autoscaler to work.
> Add Kube DNS Autoscaler RBAC

- cluster/plan.go
https://github.com/rancher/rancher/issues/11890
> Remove api runtime config

- cluster/network.go
https://github.com/rancher/rancher/issues/11447
> Disable kubeapi port check if wrap transport is used

- services/etcd.go
https://github.com/rancher/rancher/issues/11806
> Fix get etcd client issue

- cluster/cluster.go
- cluster/plan.go
- services/healthcheck.go
- services/kubeapi.go
- services/kubecontroller.go
- services/kubelet.go
- services/kubeproxy.go
- services/scheduler.go
- services/workerplane.go
> Secure kubelet port access

- cluster/cluster.go
- cluster/network.go
- cluster/reconcile.go
- cmd/up.go
- hosts/hosts.go
- services/controlplane.go
- services/etcd.go
- services/workerplane.go
https://github.com/rancher/rke/issues/390
https://github.com/rancher/rancher/issues/12083
> Updat only option and disable worker port check

- cluster/cluster.go
- cluster/logs.go
- cluster/reconcile.go
- cmd/up.go
- services/controlplane.go
- services/etcd.go
- services/kubeapi.go
- services/kubecontroller.go
- services/kubelet.go
- services/kubeproxy.go
- services/proxy.go
- services/scheduler.go
- services/services.go
- services/workerplane.go
https://github.com/rancher/rke/issues/412
> Log RKE components to a specific location

- cluster/plan.go
This change allows component attribute `extra_args` to override existing arg=values if they exist.
This PR solves #275
> Support component command argument overrides

- cluster.yml
- cluster/addons.go
- cluster/hosts.go
- cluster/plan.go
- k8s/node.go
https://github.com/rancher/rke/issues/434 
will update vendors when types [PR](https://github.com/rancher/types/pull/311) is merged
> Add AWS cloud provider support

- README.md
- cluster.yml
- cluster/addons.go
Reopening  #421 
Added yaml validation
> Adding support for urls and file paths

- cluster/cluster.go
- cluster/logs.go
> Update only for pre-pull and log cleanup

- README.md
- cluster.yml
> Update docs to reflect new extra_args

- cluster/addons.go
> Make sure we properly separate included addon manifests

- cluster/plan.go
https://github.com/rancher/rancher/issues/12398
> fix kubelet and kubeapi params

- cluster/cloud-provider.go
- cluster/cluster.go
- cluster/defaults.go
- cluster/hosts.go
- cluster/plan.go
- cluster/reconcile.go
- hosts/hosts.go
- pki/deploy.go
- services/controlplane.go
- services/etcd.go
- services/services.go
- services/workerplane.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
Depends on https://github.com/rancher/types/pull/365
> Add prefix path to services and generate plan

- cluster/plan.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go
https://github.com/rancher/types/pull/374
https://github.com/rancher/rke/issues/511
> Use kubernetes major version for service options

- cluster/defaults.go
https://github.com/rancher/rke/issues/510
> Kubernetes system image takes precedence over cluster kubernetes version

- cluster/plan.go
https://github.com/rancher/rancher/issues/12767
> bind /var/lib/rancher in kubelet

- cmd/up.go
When Rancher calls ClusterUp if err is nil we assume the full cluster config is applied.  Currently if a host can not be contacted it is dropped from the list and provisioning goes forward.  In this situation we want an error to be returned.  If one host is inaccessible it shouldn't block all provisioning but it also shouldn't return "success".
> Return error when a host is inactive

- cmd/config.go
This PR adds a prompt during config to add user addons with either URLS or file paths at the end of the config prompt
```bash
[+] Add addon manifest urls or yaml files [no]: yes
[+] Enter the Path or URL for the manifest [none]: /test/manifest.yml
[+] Add another addon [no]: 
```
> Prompt for addon paths and urls

- cluster/certificates.go
- cluster/cluster.go
- cluster/plan.go
- services/etcd.go
- services/etcd_util.go
- Deploy backup certificates on full plane instead of single node
https://github.com/rancher/rancher/issues/12873
- Fix etcd listen address edge case when public address is DNATed
Fix etcd client endpoint address 
https://github.com/rancher/rke/issues/527
> Backup certs

- cluster/state.go
https://github.com/rancher/rancher/issues/12898
> Get certificates for active etcd servers only

- cluster/certificates.go
- cluster/state.go
- pki/deploy.go
https://github.com/rancher/rancher/issues/12873
https://github.com/rancher/rancher/issues/12898
> Handle missing backup kube-etcd gracefully

- cmd/up.go
https://github.com/rancher/rancher/issues/13170
> Add updated cluster config to the k8s state

- addons/kubedns.go
- cluster/addons.go
- cluster/cluster.go
- services/controlplane.go
- services/healthcheck.go
- services/kubeapi.go
- templates/kubedns.go
https://github.com/rancher/rke/issues/235
> Fix health check when RBAC is disabled

- cluster.yml
fix incorrect kube-api service cluster ip range in the example cluster.yml.
> update kube-api service cluster ip range

- cluster/reconcile.go
https://github.com/rancher/rancher/issues/13179
> Add more log info when deleting k8s nodes

- cluster/plan.go
- services/services.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go
https://github.com/rancher/rke/issues/515
> Container labels

- templates/kubedns.go
> Add pod antiaffinity to kubedns template

- README.md
- cluster.yml
- cluster/addons.go
- cluster/cluster.go
- cluster/defaults.go
- cluster/network.go
- k8s/job.go
- k8s/k8s.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
https://github.com/rancher/rke/issues/583
~~https://github.com/rancher/types/pull/421~~
https://github.com/rancher/types/pull/424
> Critical and non-critical addons

- cluster.yml
- cluster/cluster.go
- cluster/defaults.go
- cluster/hosts.go
- cluster/network.go
- hosts/dialer.go
- hosts/hosts.go
- hosts/tunnel.go
Depend on https://github.com/rancher/types/pull/422
#103
> use Bastion/Jump host

- README.md
> kuberntest_version > kubernetes_version

- README.md
- cluster/certificates.go
https://github.com/rancher/rke/issues/613
> Fix etcd restore issue

- cluster/plan.go
- hosts/hosts.go
- services/etcd.go
> fix rhel and centos selinux relabelling regression 

- hosts/tunnel.go
> Fall back to HOMEDRIVE+HOMEPATH or USERPROFILE

- cluster/network.go
- docker/docker.go
- services/healthcheck.go
https://github.com/rancher/rke/issues/560
> Get latest logline if healthcheck fails

- cluster.yml
- cluster/defaults.go
- cluster/plan.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
https://github.com/rancher/rancher/issues/11732
https://github.com/rancher/types/pull/461
>  Add service-node-port-range for kube-api

- README.md
> Revert "Readme changes to etcd backups"

- cluster/certificates.go
- cmd/etcd.go
- pki/constants.go
- pki/pki.go
- services/etcd.go
https://github.com/rancher/rke/issues/637
> Add certificate bundle backup

- README.md
- cluster/plan.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go
https://github.com/rancher/rancher/issues/13816
Needs: https://github.com/rancher/types/pull/462
> Ability to add extra environment variables to services

- cluster/plan.go
- docker/docker.go
https://github.com/rancher/rancher/issues/13945
> Restart related k8s services when cloud provider config is updated

- cluster/certificates.go
- pki/pki.go
https://github.com/rancher/rke/issues/691
https://github.com/rancher/rke/issues/690
> Fix untar tmp ssl certificates

- docker/docker.go
https://github.com/rancher/rancher/issues/13945
> Fix cloud config compare

- cluster/reconcile.go
- k8s/node.go
- services/workerplane.go
- templates/calico.go
- templates/canal.go
- templates/flannel.go
- templates/job-deployer.go
- templates/weave.go
https://github.com/rancher/rancher/issues/14145
> Change controlplane taint to NoSchedule

- cluster/plan.go
https://github.com/rancher/rancher/issues/14151
> Register control plane node with taint

- cluster/hosts.go
- cluster/plan.go
- cluster/reconcile.go
- hosts/hosts.go
- hosts/tunnel.go
https://github.com/rancher/rke/issues/704
> Fix reconcile for ros prefix

- k8s/node.go
> Fix sync labels and taints panic

- pki/pki.go
https://github.com/rancher/rke/issues/735
> make sure tmp dir path exists before saving cert bundle

- cluster/plan.go
- services/services.go
https://github.com/rancher/rke/issues/662
> Fix container log location for ros

- cmd/remove.go
- main.go
https://github.com/rancher/rke/issues/721
> Log version

- cluster/plan.go
https://github.com/rancher/rke/issues/698
> Add hostname-override to kube-proxy

- cluster/logs.go
- hosts/hosts.go
- services/services.go
https://github.com/rancher/rke/issues/733
> Remove container dead log links on cluster remove

- cluster/plan.go
https://github.com/rancher/rke/issues/701
> Set cluster-cidr on kube-proxy

- k8s/job.go
https://github.com/rancher/rke/issues/718
> Update log message

- cluster/plan.go
https://github.com/rancher/rke/issues/750
> Allow etcd parameters to be overridden

- .drone.yml
Tested using https://github.com/superseb/drone-prerelease-release-test/releases
https://github.com/rancher/rke/issues/581
> Add prerelease when tag contains *rc*

- templates/calico.go
- templates/canal.go
https://github.com/rancher/rke/issues/681
- Disables file logging
- Disables syslog logging
- Enables stdout logging, level `Warning` as `Info` is way too verbose.
> Decrease calico/canal logging

- templates/nginx-ingress.go
Related issue https://github.com/rancher/rancher/issues/14052
> Add authorization for nginx-ingress to get daemonsets

- docker/docker.go
> Restart components if binds changed

- templates/calico.go
- templates/canal.go
https://github.com/rancher/rancher/issues/14613
> Remove description from templates

- cluster/network.go
- docker/docker.go
- pki/pki.go
- services/etcd.go
- services/healthcheck.go
https://github.com/rancher/rke/issues/768
> Add etcd snapshot fix and more log messages to certificate bundle

- services/controlplane.go
https://github.com/rancher/rancher/issues/14657
https://github.com/rancher/rke/issues/797
> Fix broken thread for controlplane processes

- docker/docker.go
https://github.com/rancher/rancher/issues/14471
> Correctly compare image env and container env

- cluster/addons.go
https://github.com/rancher/rke/issues/771
> Increase addon delete job timeout

- hosts/dialer.go
https://github.com/rancher/rke/issues/59
> Add better error when node is unreachable

- pki/pki.go
> Fixed snapshot restore unable to archive pki bundle

- pki/pki.go
https://github.com/rancher/rke/issues/821
> Remove trailing slash from tmp cert path

- docker/docker.go
> handle image upgrade

- cluster/reconcile.go
- k8s/node.go
- services/workerplane.go
https://github.com/rancher/rancher/issues/14896
> Fix resoncile missing taints

- cluster/plan.go
Note: For this to work in rancher we need to add the semver package to vendor.conf.
> Handle entrypoint upgrade across versions

- cluster/plan.go
https://github.com/rancher/rke/issues/855
> Avoid panic in rke-tools entrypoint detection

- cluster/validation.go
https://github.com/rancher/rke/issues/862
> Validate hostname_override values

- hosts/dialer.go
https://github.com/rancher/rke/issues/734
> Skip check for private key if using ssh agent

- cluster/plan.go
- docker/docker.go
https://github.com/rancher/rke/issues/588
Note: this change will require a new rke-tools image.
> Add docker config file environment variables for kubelet

- cluster/validation.go
https://github.com/rancher/rancher/issues/13660
> Update log message for validate node count

- cmd/config.go
https://github.com/rancher/rke/issues/889
> Generate system image list for k8s versions

- cluster/defaults.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/machine_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
- vendor/github.com/rancher/types/apis/project.cattle.io/v3/app_types.go
- vendor/github.com/ugorji/go/.travis.yml
- vendor/github.com/ugorji/go/LICENSE
- vendor/github.com/ugorji/go/README.md
- vendor/github.com/ugorji/go/msgpack.org.md
https://github.com/rancher/rke/issues/890
> Use default registry

- cluster/certificates.go
> Avoid panic if cert or key of a secret is not found

- services/etcd.go
> Add full path to etcd snapshots to fix windows restore

- cluster/certificates.go
https://github.com/rancher/rke/issues/866
> Fix requestheaqder ca certificate regeneration

- cluster/state.go
- pki/constants.go
- pki/deploy.go
https://github.com/rancher/rancher/issues/15422
> Save state to the nodes backup path

- templates/canal.go
https://github.com/rancher/rke/issues/903
> Mounting xtables lock within canal pod

- cluster/cluster.go
- cluster/reconcile.go
- cmd/up.go
https://github.com/rancher/rancher/issues/15810
> Handle deleting all controlplane nodes when nodes are unreachable

- docker/docker.go
- services/etcd.go
https://github.com/rancher/rancher/issues/15695
> Revert back to 5 seconds for stop timeout

- cluster/hosts.go
- cluster/plan.go
- cluster/reconcile.go
- hosts/tunnel.go
- util/util.go
https://github.com/rancher/rke/issues/931
> Use clusterversion to check supported Docker versions

- cluster/reconcile.go
- cluster/state.go
- hosts/hosts.go
https://github.com/rancher/rancher/issues/15810
> Allow replacing a single contorl node

- cluster/addons.go
- templates/metrics.go
https://github.com/rancher/rancher/issues/15940
> Handle upgrade from metrics server 0.2.x to 0.3.x

- Dockerfile.dapper
- templates/nginx-ingress.go
https://github.com/rancher/rke/issues/962
> Moving extra_args iteration to allow extra_args to work successfully

- Dockerfile.dapper
- cluster/plan.go
- docker/docker.go
- scripts/build
Same changes as for Rancher: https://github.com/rancher/rancher/pull/15331
> Update to Golang 1.11

- cluster/state.go
- pki/pki.go
https://github.com/rancher/rke/issues/958
Depends on:
https://github.com/rancher/rke-tools/pull/26
> Fix scaling problems with cluster state deployer

- cluster/defaults.go
https://github.com/rancher/rke/issues/888
> Enable etcd snapshot by default

- cluster/defaults.go
- services/etcd.go
https://github.com/rancher/rancher/issues/16511
> Fix broken etcd rolling snapshot for v0.1

- cluster/defaults.go
- services/etcd.go
https://github.com/rancher/rancher/issues/16511
> Fix broken etcd rolling snapshot

- services/etcd.go
https://github.com/rancher/rancher/issues/16551
> add restart policy to snapshot container

- cluster/defaults.go
https://github.com/rancher/rancher/issues/16294
> Force lowercase node names

- cluster/defaults.go
https://github.com/rancher/rancher/issues/16294
> Force lowercase node names - v0.1

- cluster/defaults.go
- cluster/network.go
- templates/weave.go
While trying to fix https://github.com/rancher/rke/pull/781 it was mistankely closed. This hopefully fixes the tests, and brings it all up to date.
> Add weave encryption support

- cluster/etcd.go
- cluster/network.go
- cluster/remove.go
- cmd/etcd.go
- docker/docker.go
- pki/pki.go
- services/etcd.go
- services/healthcheck.go
- services/services.go
Restore after refactor will:
- clean old kubernetes cluster
- checksum on snapshot on different hosts
- restore snapshot
- build k8s cluster (rke init & rke up)
- restart old pods
- reconcile old nodes
> refactor etcd restoration process

- cluster/state.go
https://github.com/rancher/rke/issues/947
https://github.com/rancher/rancher/issues/16975
https://github.com/rancher/rancher/issues/16934
> copy kubernetes service ip when regenerating etcd certs

- cluster/certificates.go
- cluster/cluster.go
- cluster/defaults.go
- cluster/state.go
- cmd/cert.go
- cmd/common.go
- cmd/up.go
- pki/pki.go
- pki/services.go
- pki/util.go
> Custom certificate and csr generation

- cluster/plan.go
- docker/docker.go
- pki/deploy.go
https://github.com/rancher/rke/issues/1074
> Avoid creating dangling volumes with rke tools

- cmd/up.go
- dind/dind.go
- util/util.go
Work around systemd-resolvd for dind
Add dind-dns-server option
Set sysctl configration for calico
https://github.com/rancher/rke/issues/915
> Fix dind systemd-resolvd

- services/etcd.go
https://github.com/rancher/rancher/issues/17503
> Fix s3 backup download issues

- addons/coredns.go
- addons/kubedns.go
- cluster/addons.go
- cluster/cluster.go
- cluster/defaults.go
- templates/coredns.go
- templates/kubedns.go
https://github.com/rancher/rke/issues/722
Depends on: https://github.com/rancher/types/pull/621
Ready to review
> Add CoreDNS as addon

- cluster/plan.go
on certain circumstance, kubernetes apiserver cannot detect IP address from default routes. 
this PR uses internal_address from cluster.yml to propergate "advertise-address" for mitigate this.
excerpt from kube-apiserver error
```
I1001 09:38:56.390931       1 interface.go:360] Looking for default routes with IPv4 addresses
I1001 09:38:56.390938       1 interface.go:365] Default route transits interface "eth0.100"
I1001 09:38:56.392911       1 interface.go:174] Interface eth0.100 is up
I1001 09:38:56.392970       1 interface.go:222] Interface "eth0.100" has 1 addresses :[fe80::266e:96ff:fed4:954e/64].
I1001 09:38:56.392983       1 interface.go:189] Checking addr  fe80::266e:96ff:fed4:954e/64.
I1001 09:38:56.392989       1 interface.go:202] fe80::266e:96ff:fed4:954e is not an IPv4 address …
```
> advertise address on kube-apiserver by internal_address

- cluster/cluster.go
- services/etcd.go
https://github.com/rancher/rke/issues/339
> Check if etcd is healthy before running kubeapi

- cmd/etcd.go
https://github.com/rancher/rke/issues/1119
> Update help message

- cmd/common.go
- cmd/etcd.go
- cmd/up.go
- templates/canal.go
https://github.com/rancher/rancher/issues/18035
> Handle legacy clusters restore

- cluster/reconcile.go
https://github.com/rancher/rancher/issues/17893
> Add retries in reconcile when delete hosts

- cluster/etcd.go
- services/etcd.go
- util/util.go
https://github.com/rancher/rancher/issues/18035
> Use supported rke-tools for backup and restore in legacy clusters

- cluster/addons.go
- cluster/defaults.go
https://github.com/rancher/rancher/issues/18100
https://github.com/rancher/rancher/issues/18030
> Fix Kubedns provider name

- cluster/addons.go
- templates/kubedns.go
https://github.com/rancher/rke/issues/1146
> Add node selector for DNS providers

- cmd/etcd.go
https://github.com/rancher/rke/issues/1119
> Fix command help message

- docker/docker.go
https://github.com/rancher/rancher/issues/18451
> Fix panic in container running check

- cmd/etcd.go
https://github.com/rancher/rancher/issues/18486
> Continue restore on when nodes are off

- cluster/etcd.go
- cluster/hosts.go
- cmd/etcd.go
https://github.com/rancher/rancher/issues/18419
> Ensure certs are availaible for restore

- Dockerfile.dapper
- docker/docker.go
https://github.com/rancher/rancher/issues/18537
> Add docker 18.06.x and 18.09.x

- cluster/cluster.go
- cluster/hosts.go
- cluster/reconcile.go
- cluster/remove.go
- cmd/etcd.go
- cmd/up.go
- hosts/hosts.go
- pki/deploy.go
https://github.com/rancher/rancher/issues/18426
> Restore backup to a new etcd plane

- cluster/state.go
- pki/services.go
https://github.com/rancher/rancher/issues/18608
> Regenerate requestheader ca for legacy clusters

- cluster/cluster.go
- cluster/network.go
https://github.com/rancher/rancher/issues/18690
> Fix restart pods for weave plugin

- Dockerfile.dapper
- cluster/plan.go
- scripts/build
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_windows_default.go
This PR includes the following changes:
- Because the cross build is not working,  Modify the build script to support cross build. 
- Add support to deploy  ARM64 k8s clusters.
Issue
https://github.com/rancher/rancher/issues/16461
> Support deploying ARM64 k8s and modify cross build script

- cluster/cluster.go
- cmd/cert.go
https://github.com/rancher/rancher/issues/18748
> Upgrade legacy kubeapi service in certificate rotation

- cmd/etcd.go
https://github.com/rancher/rancher/issues/18709
The case here is replacing _all_ cluster nodes, including Control Plane nodes, not just the Etcd Plane. if this is done, the API Endpoint for the cluster will change. Since this wasn't part of the original design of  RestoreEtcdSnapshot, the return values had to to be updated to reflect the new values.
> Change RestoreEtcdSnapshot to return updated cluster information

- services/etcd.go
https://github.com/rancher/rancher/issues/18757
> Use internal address with local backup download

- cluster/etcd.go
- cluster/validation.go
- services/etcd.go
https://github.com/rancher/rancher/issues/18793
> Don't disable all backups based on backup flag

- cluster/etcd.go
https://github.com/rancher/rancher/issues/18838
> Handle mixed providers

- cluster/addons.go
- cluster/cluster.go
https://github.com/rancher/rancher/issues/18805
> Restart Cattle agent pods and kubeapi auth pods

- services/etcd.go
https://github.com/rancher/rancher/issues/18935
> Don't restart one-time backup container

- services/etcd.go
https://github.com/rancher/rancher/issues/18918
https://github.com/rancher/rancher/issues/18659
> Clean old containers before etcdbackup operations

- services/etcd.go
https://github.com/rancher/rancher/issues/18918
> Wait for backup server to start before status check

- cluster/certificates.go
- cluster/state.go
- cmd/common.go
- cmd/etcd.go
- pki/deploy.go
- pki/util.go
https://github.com/rancher/rke/issues/1208
> Fetch certificates and state from nodes for legacy cluster

- cluster/certificates.go
https://github.com/rancher/rke/issues/1208#issuecomment-474255166
> Handle missing service account token key when fetching certs from nodes

- cluster/addons.go
- cluster/cluster.go
https://github.com/rancher/rke/issues/1214
> Restart cluster agent pod in rotate certs

- pki/services.go
https://github.com/rancher/rancher/issues/19033
> Regenerate etcd certificate from legacy cluster

- vendor.conf
- vendor/github.com/rancher/types/.drone.yml
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_windows_default.go
> vendor update: types

- util/util.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_windows_default.go
will squash commits once types pr is merged
> sync rke-tools version 0.1.28 and bump rancher/types 

- cluster/hosts.go
https://github.com/rancher/rancher/issues/19444
> Show correct filename for webhook auth config file

- cluster/state.go
https://github.com/rancher/rancher/issues/19484
> [release/v0.2] Fix fetching state with prefix path from nodes

- cluster/state.go
- cmd/common.go
- cmd/etcd.go
- util/util.go
https://github.com/rancher/rke/issues/1244
> Search for legacy state and certs when trying to upgrade

- cluster/file-deployer.go
https://github.com/rancher/rke/issues/1307
> Correct log messages for file-deployer

- cluster/certificates.go
- cluster/cluster.go
- cluster/defaults.go
- cluster/hosts.go
- cluster/reconcile.go
https://github.com/rancher/rancher/issues/16151
> Force deploy certificates if kube-apiserver cert got changed

- cluster/plan.go
- util/util.go
https://github.com/rancher/rke/issues/1312
> Add correct env vars if etcd 3.3 is used

- cloudprovider/aws/aws.go
- cloudprovider/openstack/openstack.go
> Fix cloud provider config password with hashtag issue 

- cluster/state.go
- pki/deploy.go
https://github.com/rancher/rancher/issues/19484
> [release/v0.1] Fix save and fetch state in clusters with prefix path

- cluster/plan.go
- templates/calico.go
- templates/canal.go
- util/util.go
Cherry pick of:
https://github.com/rancher/rke/pull/1318
https://github.com/rancher/rke/pull/1283
> [release/v0.2]: Cherry-pick from master for etcd 3.3 env and decrease canal/calico logging

- cluster/plan.go
> remove PersistentVolumeLabel controller

- cmd/common.go
- pki/services.go
https://github.com/rancher/rancher/issues/20381
>  fix upgrade path for clusters created before 0.1.10

- services/etcd.go
https://github.com/rancher/rancher/issues/19496
> Add etcd snapshot compression

- cluster/addons.go
https://github.com/rancher/rke/issues/1149
> Format user addon YAML before concat

- cluster/defaults.go
https://github.com/rancher/rancher/issues/19522
> CoreDNS default DNS provider for k8s 1.14 and up

- .drone.yml
First debug step for https://github.com/rancher/rke/issues/911
> Add listing of artifacts in Drone similar to CLI

- templates/coredns.go
https://github.com/rancher/rke/issues/1441
> Align coredns ttl to kubedns dnsmasq

- cluster/addons.go
- templates/kubedns.go
- templates/templates.go
Depends on https://github.com/rancher/types/pull/764
https://github.com/rancher/rke/issues/1195
> Add stubdomains to kube-dns

- k8s/pod.go
https://github.com/rancher/rancher/issues/21263
> Don't error out on pod delete IfNotFound

- k8s/pod.go
> Don't error out on pod delete IfNotFound [v0.2]

- templates/coredns.go
Backport https://github.com/rancher/rke/pull/1442
> [release/v0.2] Align coredns ttl to kubedns dnsmasq

- pki/util.go
Addresses: https://github.com/rancher/rke/issues/1414
The magic numbers are coming from the RFC: https://tools.ietf.org/html/rfc5280#section-4.2
The logic of using `usages` for certs doesn't apply for CSRs as there is no equivalent field. Wish the crypto library provided useful helper functions, but alas!
> Adding extensions for extended key usage

- cluster/reconcile.go
https://github.com/rancher/rancher/issues/21056
Problem: If certificates are empty in cluster state (or missing rkestate file), RKE and Rancher would throw NPE.
Solution: Check if certificates are present or error out (for now this situation needs manual intervention)
> Check if certificates are present in state

- cluster/reconcile.go
- services/controlplane.go
- services/etcd.go
https://github.com/rancher/rke/issues/1413
> Fix worker/controlplane reconcile logic

- cluster/defaults.go
- cluster/network.go
- templates/calico.go
- templates/flannel.go
https://github.com/rancher/rancher/issues/21475
> [release/v0.2] Update Calico/Flannel templates

- templates/flannel.go
https://github.com/rancher/rancher/issues/21489
> Remove additional flannel backend options

- cluster/defaults.go
- cluster/network.go
https://github.com/rancher/rancher/issues/21475
> Add Calico controller image for 3.7.4

- cluster/etcd.go
- services/etcd.go
https://github.com/rancher/rke/issues/1369
> Use etcd service extra_env in backup containers

- cluster/plan.go
order of preference: minor > major
> read serviceOptions from minor version first

- services/etcd.go
https://github.com/rancher/rancher/issues/21697
> Fix md5sum check for timestamped snapshots [v0.2]

- docker/docker.go
https://github.com/rancher/rancher/issues/21319
> fix panic on failed tunnel

- cmd/common.go
- cmd/etcd.go
- services/etcd.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/backup_types.go
Needs vendor of https://github.com/rancher/types/pull/918
> [release/v0.2] Add parameter for s3 folder

- main.go
- util/util.go
https://github.com/rancher/rke/issues/1473
> Log proxy environment variables if set

- authz/authz.go
- cluster/cluster.go
- templates/authz.go
https://github.com/rancher/rancher/issues/21712
> Add kubeapi proxy cluster role and role binding

- cluster/certificates.go
https://github.com/rancher/rke/issues/1405
> Fix constant kubeapi certificate regeneration

- cluster/certificates.go
- cluster/plan.go
- cluster/reconcile.go
- cluster/validation.go
- cmd/cert.go
- hosts/hosts.go
- pki/constants.go
- pki/deploy.go
- pki/pki.go
- pki/services.go
- pki/util.go
- services/etcd.go
This also includes fixes for:
https://github.com/rancher/rancher/issues/15862
https://github.com/rancher/rke/issues/1479
> Add per node kubelet server certificate

- cluster/certificates.go
- cluster/plan.go
- cluster/reconcile.go
- cluster/validation.go
- cmd/cert.go
- hosts/hosts.go
- pki/constants.go
- pki/deploy.go
- pki/pki.go
- pki/services.go
- pki/util.go
- services/etcd.go
Reverts rancher/rke#1522
Decided to move this out of 2.3 because of the work needed on the Rancher side for workers and time constraints
> Revert "Add per node kubelet server certificate"

- authz/psp.go
- cluster/addons.go
- cluster/cluster.go
- k8s/role.go
- templates/authz.go
https://github.com/rancher/rke/issues/1474
> Fix ingress deployment issue with PSP enabled

- templates/authz.go
https://github.com/rancher/rancher/issues/22082
> [v0.1] Add node subresources to api server cluster role

- templates/authz.go
https://github.com/rancher/rancher/issues/22083
> [v0.2] Add node subresources to api server cluster role

- templates/authz.go
https://github.com/rancher/rancher/issues/22081
> Add node subresources to api server cluster role

- Dockerfile.dapper
- cluster/plan.go
Backports one commit to fix cloudconfig checksum
> [release/v0.1] Update Go to 1.12.9

- cluster/etcd.go
- services/etcd.go
https://github.com/rancher/rancher/issues/21710
> Remove uncompressed snapshot after restore

- cluster/cluster.go
https://github.com/rancher/rke/issues/1577
> Print original error regarding kubeconfig

- metadata/metadata.go
https://github.com/rancher/rancher/issues/22269
> use go-version for comparison

- cmd/etcd.go
- services/etcd.go
https://github.com/rancher/rke/issues/1480
https://github.com/rancher/rke/issues/1495
> Improve etcd snapshot logging

- metadata/metadata.go
https://github.com/rancher/rancher/issues/21764
> read rke version correctly

- services/etcd.go
Follow up on https://github.com/rancher/rke/pull/1580
> Sync log messages for etcd snapshot containers

- cmd/config.go
- scripts/integration
Addresses https://github.com/rancher/rancher/issues/20781
> changed to Debugf, removed unneeded grep

- cluster/certificates.go
- cmd/common.go
- pki/deploy.go
https://github.com/rancher/rancher/issues/20381
> Handle missing request header ca in rotate certificate

- services/services.go
https://github.com/rancher/rancher/issues/22481
> Apply MCS label when privileged is false

- cmd/cert.go
- cmd/etcd.go
- cmd/remove.go
- cmd/up.go
- cmd/version.go
https://github.com/rancher/rke/issues/1560
> print version

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-driver-metadata/rke/templates/coredns.go
- vendor/modules.txt
https://github.com/rancher/rancher/issues/22617
> Bump rke with kontainer-driver-metadata commit

- docker/docker.go
Log seen when testing:
```
DEBU[0023] slice is not equal, showing data in old value which is not in new value: map[label=disable:{}]                                                                                                                                                                                                                     
```
Options here are:
- Set disable label ourselves, but this will change all existing setups
- Only do that for selinux enabled nodes, but it also happens on Ubuntu (or any OS I would say) where `selinux-enabled:true` is present
- While diffing the options, see if the result exactly matches the `label=disable` label and ignore.
> Ignore label=disable when comparing containers

- services/etcd_util.go
https://github.com/rancher/rke/issues/1616
> Do not randomize etcd-servers in kube-apiserver

- cluster/cluster.go
- cmd/up.go
According to https://github.com/rancher/kontainer-engine/pull/185#discussion_r320865982, we also need to support upgrade the Windows service options for worker.
**Issue:**
https://github.com/rancher/rancher/issues/22470
> Support to accpet new Windows service options

- pki/deploy.go
https://github.com/rancher/rke/issues/1622
> Do not fetch kube-admin certificate from host(s)

- README.md
https://github.com/rancher/rke/issues/973
> Update README with building instructions

- cluster/plan.go
**Issue:**
https://github.com/rancher/rancher/issues/22676
> Adjust Windows worker plan

- cmd/config.go
https://github.com/rancher/rke/issues/1651
> remove windows image from rkesystemimages for rke cli

- templates/nginx-ingress.go
https://github.com/rancher/rancher/issues/23196
> Updating nginx-ingress template for supporting k8s version upgrade

- cluster/network.go
- cmd/cert.go
- cmd/up.go
A couple of stand-alone cleanups which caught my eye when preparing an incoming PR
> Sprintf usage

- cluster/etcd.go
- services/etcd_util.go
Found while looking through the RKE code.
> Remove uneeded nil check

- cluster/certificates.go
- cluster/cluster.go
- cmd/cert.go
- pki/util.go
- services/workerplane.go
This removes dead code from RKE
> Remove dead code

- hosts/hosts.go
https://github.com/rancher/rke/issues/1504
> Mount non-default docker data dir

- cmd/config.go
- hosts/hosts.go
https://github.com/rancher/rke/issues/1685
> [v0.3] initialize metadata start of cluster config action

- cluster/cluster.go
Minor code improvement. I did not see this being triggered. Simply noticed on review.
> Catch error on setNetworkOptions

- Dockerfile.dapper
- cluster/plan.go
- cmd/config.go
https://github.com/rancher/rke/issues/1718
https://github.com/rancher/rke/issues/1719
> [forward port] cherry-picks

- hosts/dialer.go
> fix ssh agent auth with bastion host

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-driver-metadata/rke/k8s_version_info.go
- vendor/modules.txt
https://github.com/rancher/rancher/issues/23689
> vendor update kontainer-driver-metadata

- cluster/plan.go
https://github.com/rancher/rancher/issues/13769
> Bind mount added for ipvs proxy mode

- cluster/plan.go
https://github.com/rancher/rancher/issues/23756
> [forwardport]Bind mount for ipvs proxy mode

- hosts/dialer.go
https://github.com/rancher/rke/issues/1670
> [release/v0.3] fix ssh agent auth with bastion host

- services/etcd.go
- services/etcd_util.go
https://github.com/rancher/rke/issues/1750
> Return proper error in etcd healthcheck

- docker/docker.go
https://github.com/rancher/rke/issues/1684
> Reduced log level to debug for image pull

- cluster/cluster.go
- cluster/encryption.go
https://github.com/rancher/rancher/issues/23835
and support for config change - restart api/rewrite secrets is config changes
https://github.com/rancher/rancher/issues/23836
> Ability to disable custom encryption

- cluster/cluster.go
- cluster/encryption.go
- docker/docker.go
https://github.com/rancher/rke/issues/1753
https://github.com/rancher/rancher/issues/23900
https://github.com/rancher/rancher/issues/23901
> [forwardport] secrets encryption and logging fixes

- cmd/cert.go
In addition to storing it on the disk
https://github.com/rancher/rke/issues/1755
> Save cluster state to k8s on cert rotation

- cmd/cert.go
In addition to storing it on the disk
https://github.com/rancher/rke/pull/1766 - original pr
https://github.com/rancher/rke/issues/1767
> [forwardport] Save cluster state to k8s on cert rotation

- cluster/defaults.go
- cluster/plan.go
https://github.com/rancherlabs/rancher-security/issues/360
> change enc provider arg, update defaults for audit log config

- cmd/cert.go
https://github.com/rancher/rancher/issues/24097
> Address panic in cert rotation code

- templates/canal.go
https://github.com/rancher/rancher/issues/23558
> [release/v0.2] Fix Canal resources for v1.15

- cluster/file-deployer.go
https://github.com/rancher/rke/issues/1814
> [release/v1.0] Deploy cloud-config file while contents are empty

- docker/docker.go
https://github.com/rancher/rke/issues/1760
> Don't retry on Docker error address already in use

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-driver-metadata/rke/templates/coredns.go
- vendor/modules.txt
https://github.com/rancher/rke/issues/1843
> kdm vendor update for coredns template

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-driver-metadata/rke/templates/coredns.go
- vendor/modules.txt
https://github.com/rancher/rke/issues/1843
> [2.3] kdm vendor update for coredns template change

- cluster/plan.go
Backport of https://github.com/rancher/rke/pull/1845
> [release/v1.0] Add debug logging for serviceoptions

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-driver-metadata/rke/k8s_windows_service_options.go
- vendor/modules.txt
https://github.com/rancher/rancher/issues/24830
> [1.0] Vendor v117 windows fix2

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-driver-metadata/rke/k8s_windows_service_options.go
- vendor/modules.txt
https://github.com/rancher/rancher/issues/24830
> Vendor changes

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-driver-metadata/rke/templates/coredns.go
- vendor/modules.txt
https://github.com/rancher/rancher/issues/24854
> [2.3] vendor update

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-driver-metadata/rke/templates/coredns.go
- vendor/modules.txt
https://github.com/rancher/rancher/issues/24854
> vendor update

- cluster/defaults.go
https://github.com/rancher/rancher/issues/25153
> change the apiVersion of eventratelimit

- cluster/etcd.go
- services/etcd.go
https://github.com/rancher/rke/issues/1538
> Determine etcd s3 snapshots by s3 config presence

- cluster/cluster.go
- cluster/plan.go
- cluster/reconcile.go
Forwardport of https://github.com/rancher/rancher/pull/25622 
it's unexpected to see empty service options, but node plan shouldn't be generated
in those scenarios
https://github.com/rancher/rancher/issues/23284
> error out if service options are not found

- cluster/cluster.go
- cmd/up.go
https://github.com/rancher/rke/issues/1934
https://github.com/rancher/rancher/issues/25685
> Check role before including host in inactive host list

- cluster/hosts.go
- k8s/node.go
- services/controlplane.go
- services/node_util.go
https://github.com/rancher/rancher/issues/25606
https://github.com/rancher/rancher/issues/25599
> Rename ignore label and return error on controlplane failure

- hosts/tunnel.go
https://github.com/rancher/rke/issues/1940
> Add host to logging for Docker

- go.mod
- go.sum
- vendor/github.com/rancher/norman/controller/cluster_check.go
- vendor/github.com/rancher/norman/controller/generic_controller.go
- vendor/github.com/rancher/norman/objectclient/object_client.go
- vendor/github.com/rancher/norman/types/reflection.go
- vendor/modules.txt
https://github.com/rancher/rancher/issues/25965
Includes:
* https://github.com/rancher/norman/pull/355
* https://github.com/rancher/norman/pull/345
* https://github.com/rancher/norman/pull/353
> vendor norman

- cluster/defaults.go
https://github.com/rancher/rancher/issues/25992
> Retain user-configured dnsConfig fields when provider is not set

- cmd/up.go
If restore flag is set to true on RKEConfig, the reconcileCluster flag in
ClusterUp should not be set to true, so that DeployControlPlane and DeployWorkerPlane
call the non-zero downtime upgrade functions RunControlPlane and RunWorkerPlane respectively
> Use non-zero downtime upgrade logic during restore

- cluster/cluster.go
- k8s/node.go
- services/controlplane.go
https://github.com/rancher/rancher/issues/25599
> Reset error to nil if lister works on retries

- cmd/etcd.go
**Issue:**
https://github.com/rancher/rke/issues/1928
> Skip restore if no valid certs

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-driver-metadata/rke/k8s_service_options.go
- vendor/modules.txt
Includes:
- https://github.com/rancher/kontainer-driver-metadata/pull/164
> [release/v1.0] vendor kdm

- cmd/etcd.go
**Issue:**
https://github.com/rancher/rke/issues/1975
> No longer add first errors twice

- cluster/cluster.go
- services/controlplane.go
- services/workerplane.go
https://github.com/rancher/rancher/issues/26154
> Reconcile workerplane for NotReady control hosts

- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go
https://github.com/rancher/rancher/issues/26563
> [v2.2] vendor update types

- addons/addons.go
- cluster/addons.go
- templates/addonjob.go
Backport of https://github.com/rancher/rke/pull/1990
https://github.com/rancher/rke/issues/1916
> [release/v1.1] Remove user addons when not present

- addons/ingress.go
- cluster/addons.go
- templates/nginx-ingress.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go
https://github.com/rancher/types/pull/1150
> [0.2] v1.13.12-rancher2-2, v1.14.10-rancher1-2, v1.15.12-rancher1-1

- cluster/plan.go
- hosts/hosts.go
- services/services.go
https://github.com/rancher/rancher/issues/26871
> Dont relabel volumes on upstream Docker & SELinux

- cluster/cluster.go
- cluster/defaults.go
- metadata/metadata.go
Backports https://github.com/rancher/rke/pull/2079
> [1.1] Backport revert default encryption in k8s 1.18

- templates/addonjob.go
https://github.com/rancher/rke/issues/1916
> Actually remove the resources in delete addonjob

- templates/addonjob.go
Backport of https://github.com/rancher/rke/pull/2107
> [release/v1.1] Actually remove the resources in delete addonjob

- services/node_util.go
https://github.com/rancher/rancher/issues/27618
> [Backport] Check drainInput for nil to avoid panic

- types/kdm/kdm.go
To make kdm able to read channels-rke2.yaml, a new map is added for rke2 releases
part of https://github.com/rancher/rke2/issues/42
> add rke2 data field

- cluster/etcd.go
- cluster/state.go
- cmd/etcd.go
- docker/docker.go
- pki/constants.go
- pki/deploy.go
- services/etcd.go
- services/services.go
Backport of https://github.com/rancher/rke/pull/2152
https://github.com/rancher/rke/issues/1336
> [release/v1.1] Able to include and extract state file in snapshot

- cluster/defaults.go
- cluster/state.go
- cmd/cert.go
- cmd/encryption.go
- cmd/etcd.go
- cmd/remove.go
- cmd/up.go
Backport of https://github.com/rancher/rke/pull/2186
> [release/v1.1] Add restore flag to use local state

- Dockerfile.dapper
- package/Dockerfile
This aligns with that `rancher/rancher` uses
> Update base images to Ubuntu 20.04

- cluster/remove.go
- cluster/state.go
- cmd/remove.go
- dind/dind.go
https://github.com/rancher/rke/issues/1291
> Remove statefile for dind remove

- services/etcd.go
https://github.com/rancher/rke/issues/2111
> Create loglink for etcd-rolling-snapshots

- types/rke_types.go
https://github.com/rancher/rancher/issues/28905
> set ignoreDaemonsets field as nonnullable

- cluster/plan.go
https://github.com/rancher/rke/issues/2123
This removes the unneeded port 4001 to be advertised starting with k8s 1.19 (to avoid having every etcd to be rolled when not updating to k8s 1.19)
> Don't advertise etcd port 4001 in v3.4.13 and up

- cluster/reconcile.go
- services/etcd.go
- services/etcd_util.go
Backport of https://github.com/rancher/rke/pull/2256
https://github.com/rancher/rancher/issues/24547
> [release/v1.1] Check etcd cluster health after member delete

- cluster/cluster.go
https://github.com/rancher/rke/issues/2232
> [release/v1.1] Don't clean filepath on non Windows

- hosts/hosts.go
https://github.com/rancher/rke/issues/2266
> [release/v1.1] hosts: mapping Flatcar from the docker host info

- dind/dind.go
- scripts/integration
Backport of https://github.com/rancher/rke/pull/2098
> [release/v1.1] Check rollout status in integration test

- cluster/reconcile.go
- services/etcd.go
- services/etcd_util.go
~This is draft because its for v2.5.2 (and v2.4.9)~
https://github.com/rancher/rancher/issues/24547
> Check etcd cluster health after member delete

- cluster/reconcile.go
- services/etcd.go
- services/etcd_util.go
Backport of https://github.com/rancher/rke/pull/2256
https://github.com/rancher/rancher/issues/24547
> [release/v1.2] Check etcd cluster health after member delete

- scripts/integration
Backport of https://github.com/rancher/rke/pull/2253
> [release/v1.2] Add upgrade tests to integration

- k8s/k8s.go
- types/rke_types.go
https://github.com/rancher/rke/issues/2143
Backport of https://github.com/rancher/rke/pull/2141
> [release/v1.2] Updated Addon Timeout to 45s

- cluster/defaults.go
- services/controlplane.go
- services/workerplane.go
- types/rke_types.go
Forward Port PR 
https://github.com/rancher/rancher/issues/29058
> updated NodeUpgradeStrategy.Drain to use pointer

- cluster/network.go
https://github.com/rancher/rke/issues/2309
> Add retry to TCP port check

- cluster/network.go
Backport of https://github.com/rancher/rke/pull/2322
https://github.com/rancher/rke/issues/2309
> [release/v1.2] Add retry to TCP port check

- cluster/encryption.go
- cmd/encryption.go
- cmd/up.go
- log/log.go
- types/rke_types.go
- vendor/k8s.io/client-go/util/retry/OWNERS
- vendor/k8s.io/client-go/util/retry/util.go
- vendor/modules.txt
> [2.5] Encryption Key Rotation Changes (Revert)

- cluster/encryption.go
- cmd/encryption.go
- cmd/up.go
- log/log.go
- types/rke_types.go
- vendor/k8s.io/client-go/util/retry/OWNERS
- vendor/k8s.io/client-go/util/retry/util.go
- vendor/modules.txt
[Original PR](https://github.com/rancher/rke/pull/2326)
> [1.2] Encryption Key Rotation Changes

- cmd/etcd.go
https://github.com/rancher/rke/issues/2313
Add missing flags from https://github.com/rancher/rke/pull/1957 but missing from the cherry-pick in https://github.com/rancher/rke/pull/2191
> [release/v1.1] Fix backup restore with custom cert

- cluster/cluster.go
- metadata/metadata.go
https://github.com/rancher/rancher/issues/30238
> [v1.2] init metadata only if metadataInitialized is false

- cluster/cluster.go
- metadata/metadata.go
https://github.com/rancher/rancher/issues/30224
backport https://github.com/rancher/rke/pull/2389
> [v1.1] init metadata only if metadataInitialized is false

- cluster/cluster.go
- cluster/encryption.go
Previous PR:
- rancher/rke#2387
> Key Rotation- Enhance Logging, Reduce Workers

- services/kubeapi.go
backport https://github.com/rancher/rke/pull/2396
> [release/v1.2] controlplane typo

- types/image/mirror.go
https://github.com/rancher/rancher/issues/30840
Backport of https://github.com/rancher/rke/pull/2414
> [release/v1.2] Exclude Cisco ACI image from mirror

- cluster/addons.go
https://github.com/rancher/rke/issues/1637
> Mark all default addons as critical

- cluster/defaults.go
- cluster/etcd.go
- docker/docker.go
- types/backup_types.go
forward port to https://github.com/rancher/rke/pull/2418
Issue https://github.com/rancher/rancher/issues/30663
Required by https://github.com/rancher/rancher/pull/30886
> [v1.2] Added etcd snapshot timeout parameter

- cluster/defaults.go
- cluster/etcd.go
- docker/docker.go
- types/backup_types.go
Issue https://github.com/rancher/rancher/issues/30663
Required by https://github.com/rancher/rancher/pull/30951
> Added etcd snapshot timeout parameter

- pki/util.go
https://github.com/rancher/rke/issues/2427
> Improve logging when using custom certs

- go.mod
- go.sum
- vendor/modules.txt
> [v1.0.16] Release

- pki/util.go
https://github.com/rancher/rke/issues/2427
Backport of https://github.com/rancher/rke/pull/2428
> [release/v1.2] Improve logging when using custom certs

- cmd/etcd.go
https://github.com/rancher/rke/issues/1501
Backport of https://github.com/rancher/rke/pull/2421
> [release/v1.2] Warn when snapshot name contains file extension

- cluster/plan.go
https://github.com/rancher/rke/issues/2217
This adds functionality similar to cloud config checksum, we add the current checksum as an environment variable, so if it changes, the logic triggers a restart of the kube-apiserver (Which doesn't happen currently so the new config is deployed but kube-apiserver is not restarted to reload the config)
> Add auditlog checksum to trigger restart on update

- cluster/plan.go
https://github.com/rancher/rke/issues/2217
Backport of https://github.com/rancher/rke/pull/2376
> [release/v1.2] Add auditlog checksum to trigger restart on update

- types/rke_types.go
> [release/v1.2] Fix JSON tags camel case for ACI network provider

- cluster/state.go
- pki/deploy.go
Backport of https://github.com/rancher/rke/pull/2483
https://github.com/rancher/rke/issues/2395
> [release/v1.2] Write kubeconfig/state with stricter permission

- cluster/plan.go
Backport of https://github.com/rancher/rke/pull/2504
> [release/v1.2] Add stricter TLS cipher for etcd v3.4.15 and up

- cluster/plan.go
Backport of https://github.com/rancher/rke/pull/2504
> [release/v1.1] Add stricter TLS cipher for etcd v3.4.15 and up

- cluster/etcd.go
- cmd/etcd.go
https://github.com/rancher/rke/issues/2492
> Dont deploy statefile if its not readable

- pki/util.go
https://github.com/rancher/rke/issues/2485
> Change cert filename to lowercase

- cluster/defaults.go
https://github.com/rancher/rancher/issues/30356
> set ingress default backend to false for k8s 1.21+

- scripts/integration
Cherry-pick to help debugging CI runs
> [release/v1.1] output pods of all ns if rollout fails for tests

- hosts/tunnel.go
https://github.com/rancher/rancher/issues/32726
> use docker client with api negotiation

- cluster/cluster.go
- cluster/file-deployer.go
- cluster/plan.go
- hosts/hosts.go
- pki/deploy.go
- pki/pki.go
- services/controlplane.go
- services/etcd.go
- services/services.go
Requires https://github.com/rancher/rancher-selinux/pull/6
> Do not rewrite SELinux labels on volume mounts

- .drone.yml
Backport https://github.com/rancher/rke/pull/2558
> [release/v1.2] Add title to (pre) release

- .drone.yml
Backport https://github.com/rancher/rke/pull/2558
> [release/v1.1] Add title to (pre) release

- cluster/plan.go
- cluster/validation.go
- types/rke_types.go
https://github.com/rancher/rancher/issues/31943
> Add cridockerd

- hosts/hosts.go
https://github.com/rancher/rancher/issues/33132
This was introduced in https://github.com/rancher/rke/pull/2553
> Update SecurityOptions format for Docker API

- types/rke_types.go
https://github.com/rancher/rancher/issues/33358
> Fix case for CRI Dockerd JSON key

- scripts/integration
Backport of https://github.com/rancher/rke/pull/2588/commits/af3a22ab3347a5e4483f61a416e9a210d12d9e13
> [release/v1.2] Fix checking exit code in CI

- Dockerfile.dapper
- go.sum
Backport of https://github.com/rancher/rke/pull/2549
> [release/v1.2] Pin Golang to 1.16.4

- scripts/integration
Backport of https://github.com/rancher/rke/pull/2588/commits/af3a22ab3347a5e4483f61a416e9a210d12d9e13
> [release/v1.1] Fix checking exit code in CI

- .drone.yml
- scripts/package
- Scope steps to events and instances so they don't run needlessly.
- Remove artifacts as they are not used
> Clean up Drone CI steps

- pki/services.go
fix for https://github.com/rancher/rke/issues/2571
> fix custom certs csr generation for node changes

- cluster/cluster.go
- cluster/network.go
- cluster/validation.go
- pki/pki.go
- pki/pki_test.go
- pki/util.go
https://github.com/rancher/rancher/issues/33107
> Make it possible to configure dualstack

- cluster/state.go
addresses https://github.com/rancher/rke/issues/2559
continue of https://github.com/rancher/rke/pull/2562
> set EncryptionConfig on DesiredState when using CustomCerts

- cluster/addons.go
- cluster/defaults.go
- cluster/validation.go
- types/rke_types.go
https://github.com/rancher/rancher/issues/32797
> Validate Ingress Webhook and pass to template

- .dockerignore
- .drone.yml
- dind/dind.go
- scripts/integration
- scripts/package
> [release/v1.2] Drone fixes

- cluster/defaults.go
https://github.com/rancher/rancher/issues/33792
> Set ingress to hostport in k8s 1.21 and up

- cluster/cluster.go
- cluster/file-deployer.go
- cluster/plan.go
- hosts/hosts.go
- pki/deploy.go
- pki/pki.go
- services/controlplane.go
- services/etcd.go
- services/services.go
Reverts rancher/rke#2541
Based on design discussion from yesterday
> Revert "Do not rewrite SELinux labels on volume mounts"

- services/etcd.go
Backports https://github.com/rancher/rke/commit/313f3635a64b73e7b807a956ed1fd92176fb8d42.
KDM PR: https://github.com/rancher/kontainer-driver-metadata/pull/634
Related Issue: https://github.com/rancher/rancher/issues/33835
> [Backport 1.1.x] Base64 encoding etcd backup S3 accessKey and secretKey and passing them as env variables to rke-tools

- cluster/addons.go
- k8s/job.go
Forward https://github.com/rancher/rke/pull/2655
Issue https://github.com/rancher/rancher/issues/34115
> Updated nginx ingress addon to remove admission batch jobs if they exist

- cluster/encryption.go
rke 1.3.1 and 1.3.0 are failing to up a cluster when `services.kube_api.secrets_encryption_config.custom_config` is added in the cluster.yml file
Adding secrets_encryption_config data to the cluster.yml, following rke docs [secrets-encryption](https://rancher.com/docs/rke/latest/en/config-options/secrets-encryption/) format
```
kube-api:
...
secrets_encryption_config:
custom_config:
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
- resources:
- secrets
providers:
- aescbc:
keys:
- name: k-fw5hn
secret: RTczRjFDODMwQzAyMDVBREU4NDJBMUZFNDhCNzM5N0I=
- identity: {}
enabled: true
...
```
The rke up execution is finishing with this fatal. 
```
INFO[0000] Running RKE version: v1.3.1
FATA[0000] Failed to parse cluster file: unexpected type: *schema.GroupVersionKind …
```
> Update cluster.parseCustomConfig function to proper decode custom EncryptionConfiguration

- cluster/addons.go
https://github.com/rancher/rancher/issues/35766
Ingresses created before ingressClass was required do not have it set, which means that upgrading to the new ingress controller will make the ingress controller ignore the ingresses without ingressClass set and ingresses will stop working. This option will allow ingresses to keep working as it watches ingresses without ingressClass. If the user wants to disable this behavior, they can use:
```
ingress:
provider: nginx
extra_args:
watch-ingress-without-class: "false"
```
> [release/v1.3] Set 'watch-ingress-without-class: true' as default

- scripts/integration
* In case nginx admission-create and admission-patch jobs fail, this was not caught before.
> [release/v1.3] Add job complete check in integration

- k8s/job.go
This adds an additional check to ensure that a job isn't currently being deleted before attempting to create a new one and proceed with reconciliation. If the job is being deleted, we now attempt to wait for either completion, or timeout and attempt reconciliation again.
Related Issue: rancher/rancher#35750
> Retry query job status when addon is removing during apply

- cluster/addons.go
Fix of this: https://github.com/rancher/rke/pull/2900#discussion_r850613706
> Fix error handling

- go.mod
- go.sum
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>
> Version bumps

- README.md
- codegen/codegen.go
Pending https://github.com/rancher/kontainer-driver-metadata/pull/905
> Switch to release-v2.6

- .github/workflows/README.md
- Dockerfile.dapper
Describe what workflows we implemented and why
> [release/v1.3] Add GitHub Actions workflows README

- cluster/addons.go
According to https://github.com/rancher/rancher/issues/36985#issuecomment-1139800798, this PR is to revert https://github.com/rancher/rke/pull/2915
Part of: https://github.com/rancher/rancher/issues/36985
> Add logic to fix coreDNS addon config issue.

- cluster/addons.go
- k8s/job.go
This is forward port PR, see https://github.com/rancher/rke/pull/3033 for original PR. 
Issues:
https://github.com/rancher/rancher/issues/38703 
https://github.com/rancher/rancher/issues/38749
> [release/v1.4] update user addon logic to delete job, not addons

- cluster/etcd.go
https://github.com/rancher/rke/issues/3028
> [v1.3] fix panic in etcd snapshot logic 

- .github/workflows/update-readme.yml
This adds adding 1.4.x to the README when using the workflow, also simplifies the logic a bit.
> [release/v1.4] Update README workflow for v1.4.x

- cluster/defaults.go
fix for issue: https://github.com/rancher/rancher/issues/39729
> [2.6] added check for empty updatestrategy while setting dns addon defaults

- cluster/etcd.go
https://github.com/rancher/rke/issues/3099
> [release/v1.4] Check backupconfig exists before checking s3 cfg

- cluster/defaults.go
- cluster/network.go
- types/rke_types.go
https://github.com/rancher/rancher/issues/41148
> [Backport]: Add new variables for ACI-CNI 5.2.3.6

- cluster/defaults.go
- cluster/network.go
- types/rke_types.go
https://github.com/rancher/rancher/issues/41124
> Add new variables for ACI-CNI 5.2.3.6

- codegen/codegen.go
Ran go generate, no changes due to https://github.com/rancher/rke/commit/040e3591a37d9e1bcd12d701e7a760d74e15f9cc#diff-3466043f4e9c80fbf070c00304829621b1a0fb888faf131d1235db2e026c65aa
> Switch to release-v2.7

- cluster/cluster.go
https://github.com/rancher/rancher/issues/39520
> Add sandbox image to images to pre-pull

- .github/workflows/update-readme.yml
backport the PR https://github.com/rancher/rke/pull/3112
> [backport] Improve getting releases/tags when updating README

- README-template.md
- docs/troubleshooting.md
README is generated using workflow because of retrieving versions that are included
> update README and add troubleshooting doc links

- codegen/codegen.go
No change in data.json cuz latest RC already has the updated k8s versions https://github.com/rancher/rke/releases/v1.4.8-rc4
> [v1.4.8] update kdm branch to release-v2.7

- codegen/codegen.go
No change in data.json cuz latest RC already has the updated k8s versions https://github.com/rancher/rke/releases/v1.3.23-rc1
> [v1.3] update kdm branch to release-v2.6

- .drone.yml
- Dockerfile.dapper
- dind/dind.go
- package/Dockerfile
- scripts/package
- scripts/test
Same as https://github.com/rancher/rke/pull/3174
> [release/v1.5] Move to BCI

- cluster/plan.go
- go.mod
Same as https://github.com/rancher/rke/pull/3272
> [release/v1.5] Add env var to enable dual-stack in cri-dockerd

- metadata/metadata.go
issue: https://github.com/rancher/rancher/issues/42828
> [release v1.5] updated rke dev version to v1.5.99

- docs/dind.md
I tried today DinD and it was a bit hard to find information about how to run it. I dumped what I learnt in a README.md
> Add a README.md on dind with minimal information

- docs/architecture.md
Seb wrote this document which gives a lot of information around RKE1. I think we should have it in the project for anyone to learn about RKE1
> Add architecture.md

- .drone.yml
- .droneignore
- scripts/integration-ci
Backports two PRs:
https://github.com/rancher/rke/pull/3417
https://github.com/rancher/rke/pull/3394
> [Release/v1.6] Clean/speed up Drone

- README.md
Just updating the README with the latest versions.
> Update README with latest versions

- cluster/plan.go
- cluster/reconcile.go
- cmd/up.go
This reverts the PR: https://github.com/rancher/rke/pull/3531
The reverted commit will be added back after releasing v1.5.7
> Revert "Merge pull request #3531 from jiaqiluo/fix-kube-apiserver"

- cluster/defaults.go
- cluster/network.go
- types/rke_types.go
- types/zz_generated_deepcopy.go
Forward porting ACI CNI 6032 changes.
https://github.com/rancher/rancher/issues/43988
> [v1.6] Added ACI-CNI 6.0.3.2 variables

- codegen/codegen.go
`go generate .` does not produce any changes
> [1.4.17] Switch KDM to the release channel 

- README.md
update latest versions in readme
> [1.5] update latest versions in readme

- codegen/codegen.go
Switch KDM back to dev branch, `go generate` does not produce any changes
> [1.4] Post Release Cleanup 

- README.md
- codegen/codegen.go
Switch KDM back to dev branch, `go generate` does not produce any changes 
Update README with latest versions
> [1.5] Post Release Cleanup 

- .github/workflows/workflow.yaml
ref: https://github.com/rancher/rancher/issues/45377
Fix the dependency to run correctly on tag, since integration-ci step gets skipped when tag is pushed.
> Fix dependencies to run correctly on tag

- cluster/addons.go
- cluster/cluster.go
- cluster/state.go
- cluster/state_test.go
- cmd/cert.go
- cmd/up.go
- cmd/util.go
- k8s/secret.go
Porting https://github.com/rancher/rke/pull/3600
> [v1.6] Port fixes 478

- .github/workflows/workflow.yaml
ref: https://github.com/rancher/rancher/issues/45377
> Fix tokens for gh cli invocations

- cluster/defaults.go
- cluster/network.go
- types/rke_types.go
https://github.com/rancher/rancher/issues/45952
> [release/v1.6] Add ACI-CNI 6.0.4.2 variables

- codegen/codegen.go
https://github.com/rancher/rke/pull/3637
> [release/v1.6] Change KDM release URL to dev-v2.9 from release-v2.9 post RKE v1.6.0

- codegen/codegen.go
https://github.com/rancher/rke/pull/3636
> [release/v1.5] Change KDM release URL to dev-v2.8 from release-v2.8 post RKE v1.5.11

- codegen/codegen.go
https://github.com/rancher/rke/pull/3635
> [release/v1.4] Change KDM release URL to dev-v2.7 from release-v2.7 post RKE v1.4.20

- .github/workflows/workflow.yaml
ref issue: https://github.com/rancher/rancher/issues/46679
> Add setup to generate and upload sha256sum file

- cluster/plan.go
- types/rke_types.go
issues:
* https://github.com/rancher/rke/issues/3656
* https://github.com/rancher/rancher/issues/46871
- added stream_server_address and stream_server_port in RancherKubernetesEngineConfig
- also added env variables to pass to kubelet container for setting stream-server-addr for cri-dockerd.
> added streaming server addr configuration for cri-dockerd

- cluster/plan.go
- types/rke_types.go
issue: https://github.com/rancher/rancher/issues/46918
cherry-picked from PR: https://github.com/rancher/rke/pull/3658
> [release v1.5] added streaming server addr configuration for cri-dockerd

- services/etcd.go
Original issue in v1.5 branch is etcd client was closed incorrectly (See: https://github.com/rancher/rke/pull/3536/files#diff-258cab59034848f0d36d759a4a7ba9cf9a96b73ba12d836647b58875e3eaf46dR253) 
Since it got fixed in v1.6 branch with refactoring as part of https://github.com/rancher/rke/pull/3573, I am back porting the change. 
Issue: https://github.com/rancher/rancher/issues/47185
> [v1.5] check if etcd member in list before removal

- cluster/defaults.go
- cluster/network.go
- types/rke_types.go
https://github.com/rancher/rancher/issues/47384
> [release/v1.6] Add ACI-CNI 6.1.1.1 variables

- cluster/defaults.go
- cluster/network.go
- types/rke_types.go
https://github.com/rancher/rancher/issues/47383
> [release/v1.5] Add ACI-CNI 6.1.1.1 variables

- .github/workflows/workflow.yaml
- codegen/codegen.go
* Update KDM branch to `v2.10` in codegen (https://github.com/rancher/rke/pull/3704)
* Add `release/v2.10` as an action target branch
> [release/v1.7] Update KDM branch and add support for `release/v2.10` target branch

- codegen/codegen.go
`go generate .` does not produce any change
> [1.4] switch KDM to release branch

- codegen/codegen.go
switch KDM to the dev branch after the release is done
> [1.4] [post-release] switch KDM to the dev branch after the release is done

- cluster/defaults.go
- cluster/network.go
- types/rke_types.go
https://github.com/rancher/rancher/issues/47413
> [release/v1.7] Add ACI-CNI 6.1.1.1 variables 

- go.mod
issue: https://github.com/rancher/rancher/issues/47678
> [release/v1.7] bump go to v1.22.8

- go.mod
issue: https://github.com/rancher/rancher/issues/47678
> [release/v1.6] bump go to v1.22.8

- .github/workflows/workflow.yaml
- Action target branch for `v1.7` to rancher `release/v2.10`
- Move action target branch rancher `main` to `v1.8`
> Update action target branch

- .github/workflows/git-actions-go-generate.yml
- Bump `actions/checkout` to `v4`.  
- Bump `actions/github-script` to `v7`.
- https://github.com/rancher/rke/actions/runs/12146980071
> [v1.7] Update GitHub Actions dependencies 

- .github/workflows/git-actions-go-generate.yml
- Bump `actions/checkout` to `v4`.  
- Bump `actions/github-script` to `v7`.
- https://github.com/rancher/rke/actions/runs/12146982206
> [v1.6] Update GitHub Actions dependencies

- cluster/defaults.go
- cluster/network.go
- types/rke_types.go
https://github.com/rancher/rancher/issues/48155
> [release/v1.7] Add ACI-CNI 6.0.4.4 variables

- cluster/defaults.go
- cluster/network.go
- types/rke_types.go
https://github.com/rancher/rancher/issues/48154
> [release/v1.6] Add ACI-CNI 6.0.4.4 variables

- pki/util.go
for https://github.com/rancher/rke/pull/3695
> fix: fix slice init length

- cluster/defaults.go
- cluster/plan.go
- types/rke_types.go
- types/zz_generated_deepcopy.go
issue: https://github.com/rancher/rancher/issues/49246
- added configuration so that users can optionally opt out of enabling the br_netfilter on nodes.
> [release/v1.8] added EnableBrNetfilter configuration

- cluster/defaults.go
- cluster/plan.go
- types/rke_types.go
- types/zz_generated_deepcopy.go
https://github.com/rancher/rancher/issues/49095
> [backport][release/v1.6] added EnableBrNetfilter configuration

- .github/workflows/workflow.yaml
- GHA to support `release/v2.11` branch
- https://github.com/rancher/rancher/issues/49076
> [v1.8] Update GHA to support `release/v2.11` branch

- .github/workflows/update-readme.yml
- README-template.md
fix the workflow for updating the README file
> [1.8] fix the workflow for updating the README file

- .github/workflows/update-readme.yml
- README-template.md
Fix the workflow for updating the README file
> [1.7] fix the workflow for updating the README file
