hosts/hosts.go
k8s/node.go

https://github.com/rancher/rke/issues/70

Warn instead of fatal if deleted host is not found in k8s.

---

addons/kubedns.go
cluster.yml
cluster/addons.go
cluster/cluster.go
cluster/defaults.go
cluster/hosts.go
cluster/network.go
cluster/reconcile.go
cluster/remove.go
cmd/config.go
hosts/hosts.go
network/calico.go
network/canal.go
network/flannel.go
network/network.go
pki/constants.go
pki/deploy.go
services/proxy.go
services/workerplane.go

https://github.com/rancher/rke/issues/84

Configurable images

---

cluster/cluster.go
cluster/reconcile.go
cluster/state.go

#113 
If the current cp host is unreachable, rke will try each cp host in the list until it finds one that is working and use it to get cluster state.

Rebuild local admin if the current master host is down

---

services/kubelet.go

In order to support Flexvolume plugins on the host.
See https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md for the location of Flexvolume plugins in Kubernetes.

Add host bindmount for `/usr/libexec/kubernetes/kubelet-plugins`

---

README.md

To avoid `error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false.` error.
Although there is a workaround as stated in https://github.com/rancher/rke/issues/189#issuecomment-354661774 running without swap is preferred as discussed in https://github.com/kubernetes/kubernetes/issues/53533#issuecomment-334947625 and should be mentioned.

Added no-swap for kubelet node comment in requirements

---

.gitignore
hosts/dialer.go
hosts/local.go
hosts/tunnel.go
vendor/golang.org/x/crypto/ssh/agent/client.go
vendor/golang.org/x/crypto/ssh/agent/forward.go
vendor/golang.org/x/crypto/ssh/agent/keyring.go
vendor/golang.org/x/crypto/ssh/agent/server.go

This PR makes it so that:
1. The SSH Agent specified by SSH_AUTH_SOCK is always used. 
2. If run from an environment without the SSH Agent running it will fall back to using a non-passphrase protected private key.
- This does remove private keys with passphrases and no agent support. 
Additionally, the code was re-factored to de-duplicate some code paths with the Dial methods. 
The host object was also removed from the dialer type.

Use SSH Agent

---

cluster/hosts.go

Fixes a regression caused by how we handle connectivity failure. To handle temporary node connectivity issues we recently changed RKE behavior to just warn on connectivity problems and ignore the host for this run. 
However, this is not the expected behavior when we fail due to unsupported version when used with rancher. Since the proper error is not returned to rancher and the failure cause is not clear. So, this PR will exit with an error if the used docker version is not supported.
https://github.com/rancher/rancher/issues/12147

Error out on unsuppored docker version instead of Warn

---

cluster.yml
cluster/cluster.go
cluster/defaults.go
pki/kubeconfig.go
pki/pki.go
pki/util.go

Requires vendor bump: types.
Depends on: https://github.com/rancher/types/pull/288
This PR solves #415

Support Cluster name in Kube Config

---

README.md
cluster.yml
cluster/certificates.go
pki/pki.go
pki/util.go
vendor.conf
vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go

Support the ability to add additional hosts or IPs (Alt Names) to the PKI certs for Kube Api server.
Satisfies #86 
Depends on types: https://github.com/rancher/types/pull/305

Add additional hosts to Api Server PKI

---

cluster/cluster.go
cluster/plan.go

There seemed to be two issues here.  First, the workerNodePlanMap would only ever contain hosts that have a controlplane role.  So etcd only (maybe worker only too) nodes would not be in the map.  The second is after I fixed that, nginx is not defined for etcd only nodes.

Fix missing image for etcd only nodes

---

k8s/node.go

Related issue: https://github.com/rancher/rancher/issues/12577
even I have the hostname Small2-Node1, but k8s will add small2-node1 for the label kubernetes.io/hostname. 
I don't know whether we could use the lowercase to compare them, since the requestedHostname is dnsLabel type, so “Jabberwocky” and “jabberwocky” are both permissible domain name labels, but they are equivalent. If it not right, feel free to talk to me.

when the hostname is uppercase, k8s add lowercase hostname to the kubernetes.io/hostname

---

cluster/cluster.go

From what I can gather host.UpdateWorker is always false this point in the code.  This means we never actually pre-pull the images.  I removed this check as it doesn't seem bad to just check everyhost in the deployment always.  It should be fast.

Always try to pull

---

cluster/plan.go
pki/deploy.go

Instead of having rke-cert-deployer, rke-nginx-proxy, and alpine as supporting images, we just consolidate to one (rke-tools) as ever host is going to end up with all three images regardless.
This is missing the corresponding types change.

WIP Use new rke-tools image

---

cluster/network.go
docker/docker.go
vendor/github.com/docker/docker/pkg/README.md
vendor/github.com/docker/docker/pkg/stdcopy/stdcopy.go

https://github.com/rancher/rke/issues/507
- Added timeout of 5 seconds to `nc` command
- Added backgrounding of nc to run in parallel
- Removed TTY which enables two streams of logging (stdout and stderr)
- Added extra logline to stdout when checking ports, sending err to stderr
- Specifically set `json-file` logconfig to ensure we can read the logs
- Use docker stdcopy to copy the stderr stream and check the logs

Portcheck timeout

---

templates/job-deployer.go

Environment sometimes taking time to get stabilized..  
Initial Error
```
Failed to download OpenAPI (Get https://10.233.0.1:443/swagger-2.0.0.pb-v1: dial tcp 10.233.0.1:443: i/o timeout), falling back to swagger
Unable to connect to the server: dial tcp 10.233.0.1:443: i/o timeout
```
Eventually networking is working but taking time.. but by that time jobs are hitting backoffLimit and no executed. 
The back-off limit of K8 JOB is set default to 6 by K8s . with exponential back-off delay (10s, 20s, 40s …) capped at six minutes. 
So Setting 10 will allow sometime for job to get executed 
Partial fix for https://github.com/rancher/rke/issues/303

Fix to partially address Issue #303

---

cluster/plan.go

Fix implemented for https://github.com/rancher/rancher/issues/12776 was to remove Host Info but this would be nice to have.
Only caveat is that if `/etc/os-release` doesn't exist, it will break.

Add os-release to get proper OS info

---

cluster/plan.go

https://github.com/rancher/rke/issues/565
```
2018-05-02 11:50:12.691385 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
af4f1069717bae44, started, etcd-167.99.33.103, https://167.99.33.103:2380, https://167.99.33.103:2379,https://167.99.33.103:4001
c377226fab81158f, started, etcd-167.99.41.238, https://167.99.41.238:2380, https://167.99.41.238:2379,https://167.99.41.238:4001
e309dc3d5dbb513d, started, etcd-167.99.45.164, https://167.99.45.164:2380, https://167.99.45.164:2379,https://167.99.45.164:4001
```

Add etcd env vars for etcdctl

---

cluster/defaults.go

When using an empty network provider sent from rancher in `c.Network.CalicoNetworkProvider`, the default `none` is not set, instead, it gets overridden by the empty value. 
https://github.com/rancher/rancher/issues/13348

Fix empty default calico cloud provider

---

cluster.yml

Extra binds example prevents kubelet from starting up. The path seems to be already present when inspecting my kubelet.

removing redundant extra binds

---

cluster/plan.go

Fix override prefix path for ROS, B2D, and CoreOS

---

cmd/common.go
cmd/etcd.go
cmd/remove.go
cmd/up.go

When using local, you don't need a config file, this makes it possible for
`rke up --local --ignore-docker-version`
and the corresponding
`rke remove --local --ignore-docker-version`

Added flag to ignore docker version

---

cluster/network.go

```
FATA[0011] [network] Host [x] is not able to connect to the following ports: [Y:2379, Y:2380, Z:2380, 2Z:2379]. Please check network policies and firewall rules
```
https://github.com/rancher/rke/issues/644

Improve port check error message

---

cluster/addons.go
cluster/state.go
k8s/configmap.go
k8s/job.go

https://github.com/rancher/rke/issues/584
This PR does two things
- It provides support for updating addons configuration, both system and user defined addons. 
- If fixes an issue where an addon job is skipped on re-runs even if it's not in a completed state. 
Note: It's not possible to change cluster cidr configuration using this. It's not supported by Kubernetes:
- https://github.com/kubernetes/kubernetes/issues/50305
- https://github.com/kubernetes-incubator/kube-aws/issues/1307

Add support for addons upgrades

---

cmd/remove.go
cmd/up.go
dind/dind.go
hosts/dialer.go
hosts/dind.go
services/healthcheck.go

https://github.com/rancher/rancher/issues/14266
The dind mode will enable the user to deploy nodes as docker containers locally, each docker container has docker installed within, for example to create 3 node cluster in dind mode:
cluster.yml
```
nodes:
- address: 172.18.0.9
user: ubuntu
role: [controlplane,worker,etcd]
- address: 172.18.0.10
user: ubuntu
role: [controlplane,worker,etcd]
- address: 172.18.0.11
user: ubuntu
role: [controlplane,worker,etcd]
```
and then:
```
rke up --dind
```
RKE will first create a network subnet called `dind-network` with subnet defaults to `172.18.0.0/16` and then deploy 3 nodes as docker containers and start kubernetes installation

Add dind mode to rke

---

main.go

https://github.com/rancher/rke/issues/751
```
./rke_darwin-amd64 config
WARN[0000] This is not an officially supported version (v0.1.8-rc11) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest
[+] Cluster Level SSH Private Key Path [~/.ssh/id_rsa]:
```

Add warning when using unreleased version

---

cluster/plan.go

adjusting of the volumeplugins path was missed in the PR that added prefix support.

kubelet volumeplugins path does not contain prefix

---

templates/vsphere.go

The template for creating the cloud provider config file for vsphere uses a wrong value for soap-roundtrip-count in the VirtualCenter section.
This commit fixes that. It will set the value to 0 if not specified in RKE's cluster config. That should be ok as a value of 0 means "use the default" and the default is the value set in the global section.

fixes wrong value for soap-roundtrip-count in vsphere provider

---

pki/kubeconfig.go

We use RKE to build and maintain multiple clusters.  Generally, I set KUBECONFIG to include all the generated kube_config_cluster.yml files.  However, in all of them, after generation, the context is 'Default', and the user is 'kube-admin'.  This is problematic as kubectl cannot differentiate between clusters.
This patch assures that user and context are unique per cluster.

allow overlapping kubeconfigs by appending clusterName to user and context

---

templates/nginx-ingress.go

Related issue https://github.com/rancher/rancher/issues/15044
Configmap resource data only support string data so
we should add quotation mark for each data item.

Add quotation mark for nginx-configuration

---

cluster/addons.go
templates/nginx-ingress.go

https://github.com/rancher/rke/issues/893
the PR updates the yaml template to follow the official ingress nginx deployment:
https://github.com/kubernetes/ingress-nginx/blob/nginx-0.16.2/deploy/mandatory.yaml
described in the official documentation:
https://kubernetes.github.io/ingress-nginx/deploy/

Update ingress nginx template yaml

---

cluster/addons.go
cluster/certificates.go
cluster/cluster.go
cluster/hosts.go
cluster/plan.go
cluster/reconcile.go
cmd/cert.go
cmd/up.go
docker/docker.go
k8s/pod.go
main.go
pki/constants.go
pki/deploy.go
pki/pki.go
pki/services.go
pki/util.go
services/controlplane.go
services/etcd.go
services/kubeapi.go
services/kubecontroller.go
services/kubelet.go
services/kubeproxy.go
services/proxy.go
services/scheduler.go
services/workerplane.go

https://github.com/rancher/rke/issues/450
Certificate Rotation PR includes:
- Add `rke cert rotate` command for:
- all certificates
- ca certificates (Master CA - Request header CA) `--rotate-ca`
- specific component (kubelet, kube-apiserver, kube-proxy, kube-controller-manager, kube-scheduler, etcd) eg. `--service etcd`
- Reconcile the service account token key and use different key instead of kubeapi key
Tested Scenarios:
- Run cert rotation for all certificates
- Run cert rotation for all certs and ca certs
- Run cert rotation for specific component
- Run cert rotation command on cluster created by rke v0.1.11
- Upgrade from rke v0.1.11 to master
- Run cert rotation multiple times

Add Rotate certificates option to rke

---

cluster/network.go
cluster/validation.go

Create an RKE config file like:
```
nodes:
- address: 192.168.100.129
user: docker
role:
- controlplane
- etcd
- address: 192.168.100.130
user: docker
role:
- worker
- address: 192.168.100.131
user: docker
role:
- worker
network:
plugin: none
```
https://github.com/rancher/rke/issues/873

Allow creating Kubernetes clusters without a cluster network

---

.gitignore
cluster/cluster.go
cluster/defaults.go
cluster/plan.go
cmd/up.go
scripts/ci
scripts/integration
util/util.go
vendor.conf
vendor/github.com/rancher/types/.gitignore
vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go

First in a set of recommended options for CIS Kubernetes Benchmark guidelines.
Command Options: (sorry reordered the lists alphabetically to make it easier to find options)
kubelet:
* streaming-connection-idle-timeout: "30m"
* make-iptables-util-chains: "true"
* event-qps: "0"
kubeapi:
* anonymous-auth: "false"
* unset insecure-bind-address
* profiling: "false"
* repair-malformed-updates: false
* service-account-lookup: true
* enable-admission-plugins: ...NodeRestriction...
kube-scheduler:
* profiling: "false"
* address: "127.0.0.1" ("0.0.0.0" when DinD)
kube-controller-manager:
* terminated-pod-gc-threshold: "1000"
* profiling: "false"
* address: "127.0.0.1" ("0.0.0.0" when DinD)
kube-proxy:
* healthz-bind-address: "127.0.0.1" ("0.0.0.0" when DinD)
---
Moved cadvisor-port out of global …

CIS Benchmark recommended options

---

cluster/plan.go

Option to add AlwaysPullImages admission plugin for CIS Benchmark best practices.
> Setting admission control policy to AlwaysPullImages forces every new pod to pull the
required images every time. In a multi-tenant cluster users can be assured that their
private images can only be used by those who have the credentials to pull them.
Requires rancher/types#650

CIS Benchmark - Admission Plugin AlwaysPullImages

---

cluster/network.go

**Problem:**
Port check fails for network plugins on the existing k8s cluster.
**Solution:**
revert to skip check network plugin `udp` ports, more details described in the #1102.
**Issues:**
https://github.com/rancher/rke/issues/1102
https://github.com/rancher/rancher/issues/17655
**Related PRs:**

revert to skip network plugin port checks of udp port

---

docker/docker.go

To prevent against accidental SIGSEGV errors we should verify the use
of a non-nil docker client.
For rancher/rancher/issues/17519

Add checks for nil docker client

---

hosts/dialer.go
hosts/tunnel.go
vendor.conf
vendor/github.com/rancher/types/apis/management.cattle.io/v3/globaldns_types.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/machine_types.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go
vendor/github.com/rancher/types/apis/project.cattle.io/v3/app_types.go

Implements https://github.com/rancher/rke/issues/1002
Add support for SSH certificates when using RKE. 
Pending `types` PR: https://github.com/rancher/types/pull/583
RKE fork that relies on changes: 
https://github.com/bernard-wagner/rke/tree/ssh-cert
For more background:
https://man.openbsd.org/ssh-keygen.1#CERTIFICATES
https://man.openbsd.org/sshd_config#TrustedUserCAKeys
```
$ ssh-keygen -t rsa -b 4096 -f demo-ca -q -P ""
$ cat demo-ca.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXoifoWpZ/SC5bzOSmBmCRJMM4lF2....
```
```
storage:
files:
- filesystem: root
user: 
name: root
group: 
name: root
path: /etc/ssh/ssh_trusted_user_ca_keys
mode: 0644
contents: 
inline: |
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXoifoWpZ/SC5bzOSmBmCRJMM4lF2....
- filesystem: root
path: /etc/ssh/sshd_config
contents: …
```

Add support for SSH certificate authentication

---

templates/flannel.go

In a new cluster the nodes will be NotReady until the network cni plugin is configured. Since the flannel daemonset is responsible for setting this up it needs to be able to schedule on nodes that are NotReady
Signed-off-by: Joshua Benjamin <joshuabnjmn@gmail.com>

Fix flannel startup in new cluster

---

templates/kubedns.go

**Problem:**
Schedule kubedns component to Windows node will cause DNS doesn't work
well
**Solution:**
Add nodeAffinity to kubedns
**Issue:**
https://github.com/rancher/rancher/issues/17423

Don't schedule kubedns to Windows node

---

cluster/plan.go

On the ARM64 platform, ETCD_UNSUPPORTED_ARCH env var cannot recognize `aarch64`, so we need to convert `aarch64` to `arm64`.
https://github.com/rancher/rancher/issues/16518

Convert aarch64 to arm64 for ETCD_UNSUPPORTED_ARCH env var

---

cluster/plan.go

**Problem:**
For now, Monitoring cannot scrape metrics from controllerMgr & scheduler
**Solution:**
Change listening address to `0.0.0.0`
**Issue:**
https://github.com/rancher/rancher/issues/17922

Change controllerMgr & scheduler listening address

---

cluster/addons.go

This PR ensures each YAML file in the `addons_include` section of `cluster.yml` begins with 3 dashes `---`. This is necessary so we can safely append all the manifests files regardless if they begin with `---`.
#1251.
Signed-off-by: Jesse Millan jlamillan@gmail.com

Prepend 3 dashes at the beginning of addon YAMLs. Resolve #1251

---

cluster/state.go

https://github.com/rancher/rancher/issues/17965
The fix makes sure there is prefix path included in the file path because we already bind mount the volume /etc/kubernetes with prefix path

Fix fetching state with prefix path from nodes

---

pki/services.go

https://github.com/rancher/rancher/issues/19569

Fix rotation of kubeapi certificate in legacy clusters

---

cluster/plan.go

This PR should mitigate the issue where the CNI provider in an RKE cluster fails to access iptables with the error: `iptables: Resource temporarily unavailable` leading to pod network disruption on the node. See 
https://github.com/rancher/rancher/issues/18637
`kube-proxy` and network plugins such as Flannel, Calico, etc. are all accessing iptables on the host.
Currently the kube-proxy container does not mount the common, host-level locking file (`/run/xtables.lock`), while the CNI plugins do. See https://github.com/rancher/rke/blob/master/templates/canal.go#L985-L987
This leads to racy/concurrent iptables access that may result in iptable calls to fail (`iptables: Resource temporarily unavailable` ) while CNI provider tries to ensure the required masquerade rules. In case of Flannel this …

Fix racy iptables between kube-proxy and CNI provider

---

cluster/file-deployer.go
docker/docker.go
hosts/hosts.go

https://github.com/rancher/rancher/issues/19438
* Differentiates running containers and onetime containers
* Remove the native Docker wait and implement active polling for actively checking container via Docker and to keep the tunnel active (if there is no reply within 50 seconds, the tunnel closes). This also solves etcd snaphots that take longer than 50 seconds to complete (https://github.com/rancher/rancher/issues/19496). The current hardcoded timeout is 300 retries with 1 second sleep each. (5 minutes)
* The new onetime container failed on `rke remove` due to `rm -rf` ing the bind mounted folder. This is replaced with using find like for the rke logs.

Added onetime container and active running checks

---

cluster/defaults.go
cluster/network.go
templates/canal.go
templates/flannel.go

- Add `flannel_backend_port` and `canal_flannel_backend_port` to config
the port of Flannel
- Add `flanneld_backend_vni` and `canal_flannel_backend_vni` to config
the VxLan network identify of Flannel

Support to config Flannel backend

---

templates/metrics.go
templates/nginx-ingress.go

**Problem:**
Schedule default-http-backend and metrics-server to Windows node will be failed.
**Solution:**
Add nodeAffinity to default-http-backend and metrics-server workload
spec
**Issue:**
https://github.com/rancher/rancher/issues/19929

Don't schedule Linux addons to Windows node

---

templates/calico.go
templates/canal.go

The Canal and Calico templates for K8s 1.13 introduce a regression in the use of info vs warning log level. Initial decrease of log level in the templates was made in https://github.com/rancher/rke/commit/c00e6d2e9d272ea76ce8147fb7c163a34fb369ad#diff-3497e44efe766fa9ca127075b285d611L118
This decreases log verbosity to warning in the 1.13 templates.
https://github.com/rancher/rancher/issues/19472

Decrease calico/canal logging for K8s 1.13 templates

---

cluster/plan.go

It has been deprecated, adding it to baseEnabledAdmissionPlugins results into a warning, but the controller still gets loaded and affects the behavior for persistent volume creation. 
https://github.com/rancher/rancher/issues/19749

remove PersistentVolumeLabel controller

---

cluster/network.go

This PR updates RKE's preliminary KubeAPI port check to fall back to HTTP when raw TCP fails to avoid potential firewall connectivity problems. 
Signed-off-by: Jesse Millan jlamillan@gmail.com

Do *preliminary* nc KubeAPI port check using HTTP (not raw TCP)

---

cluster/plan.go
services/etcd_util.go

Use the local etcd server first if available, and randomize the order for other etcd servers.

Reorder etcd servers list

---

cluster/etcd.go
services/etcd.go
util/util.go

we can remove dependency of etcd snapshot actions on rke-tools and just use the latest version

always use DefaultRKETools for etcd snapshot

---

templates/coredns.go
templates/kubedns.go
templates/nginx-ingress.go

#1437
Kubernetes doesn't accept any other value but string in nodeSelector,
but if we specified ambiguous value like true, it's treated as a
non-string like bool and then failed to create resource because of type
mis-match, that's why we should make value of nodeSelector enclosed by
double quotations to ensure value is always string

NodeSelector should specify string explicitly

---

cluster/etcd.go
services/etcd.go
util/util.go

- use image path from c.systemImages which has the prefixed private registry info
- get default rke tool tag from the Default K8s, that ensures this rke-tools has always been pulled in (because it has been mentioned in rancher-images.txt)  
https://github.com/rancher/rke/issues/1472

generate correct default rketools

---

cluster/reconcile.go

#1404 when configuration contains no node that use the `etcd` role.

Bug fix: Support of configuration with no node with etcd role

---

cluster/cluster.go
cluster/network.go

Problem: Calico pods are not deleted when etcd snapshot restore is done.
Root cause: The wrong k8s-label was used to select calico pods for removal (`calico` vs `calico-node`)
Fix: Provide correct labels and loop over labels to delete calico pods.
https://github.com/rancher/rancher/issues/21490
Also fixes a typo: `WeaveNetowrkAppName` -> `WeaveNetworkAppName `

Use correct labels to delete calico pods

---

util/util.go

Issue: We extract tag from the passed system image and replace it from Default k8's system image. This causes problem when the passed system image is custom, and gets overridden 
https://github.com/rancher/rke/issues/1551

don't override tag of custom system images for defaultRKETools

---

cmd/cert.go

Problem: The flag `--ssh-agent-auth` cannot be used in `rke cert` commands.
Root cause: Common flags are not added to the `cert` subcommand
Fix: Add common flags to the `cert` subcommand
https://github.com/rancher/rke/issues/1479

Make commonflags work with rke cert commands

---

cluster/plan.go
docker/docker.go
services/etcd.go
services/kubeapi.go
services/kubecontroller.go
services/kubelet.go
services/kubeproxy.go
services/proxy.go
services/scheduler.go
services/services.go

https://github.com/rancher/rke/issues/1520
As we are editing `GetProcessConfig` and Rancher also uses this function, in Rancher we will pass an empty Host to the function.

Configure MCS labels if selinux is enabled

---

cluster/cluster.go
cluster/reconcile.go

**Problem:**
We can not set node taints in RKE node config.
**Solution:**
Sync taints from config in `SyncLabelsAndTaints` function
Related issue:
https://github.com/rancher/rancher/issues/13972

Support node taints configuration

---

hosts/tunnel.go

Problem: Because of the unix socket reference, Windows breaks on rke up
Root cause: Vendor of docker/docker
Resolution: I was checking what was changed in vendor but it seems this setting is not used, as we configure Docker socket per host.
https://github.com/rancher/rke/issues/1189

Dont set withHost on Docker client

---

hosts/tunnel.go

When IgnoreDockerVersion is set, do not try to parse its version number
Still retrieve docker info to check check fi docker is reachable
https://github.com/rancher/rke/issues/1502

Do not parse docker version when validation is disabled

---

cluster/plan.go
k8s/psp.go
templates/authz.go

Pod security policy has moved from `extensions/v1beta1` to `policy/v1beta1` in 1.16
https://github.com/rancher/rancher/issues/22716

Update apis for 1.16

---

cluster/cluster.go
main.go
util/util.go

https://github.com/rancher/rke/issues/1473
Issue: Proxy environment variables were printed in main
Root cause: This means it will be printed every time and while it is only used in the rke -> kube-api check, so if we print it every time, it might confuse users that proxy is being used in other commands while they dont pass local proxy env vars to other containers executing actions.
Solution: add the log to ClusterUp so it will be used when using `rke up` and when Rancher uses it.

Print proxy env vars when applying authz resources

---

cloudprovider/aws/aws.go

Just fixing the typo in the AWS logs.

AWS: fix log typo

---

cluster/plan.go

https://github.com/rancher/rancher/issues/22814
If cloudprovider is set to aws, set the bind address because the node will not be able to retrieve it's IP address because the nodename is set by AWS to internal DNS name
Considerations taken:
- Scope it to 1.16 only: this would eliminate affecting existing setups, but that would introduce code to check for cluster version being 1.16 or higher and because its a dynamic variable (IP address is per node), it cant go in the generic getServiceOptions. This means code needs to be added in `cluster/plan.go` to scope for 1.16 or higher and this seems overly complex.
- Set address to `127.0.0.1` (which was what it autodetected to before 1.16): if we change the parameter, we can just set it to the proper value.
- A bigger plan for AWS cloudprovider …

Provide IP for kube-proxy when cloudprovider = aws

---

cluster/plan.go

https://github.com/rancher/rancher/issues/22814
If cloudprovider is set (not empty), set the bind address because the node will not be able to retrieve it's IP address because the nodename could be set by the cloud provider (e.g. AWS and Openstack)
After running into other issues that had similar logic, we changed from checking for AWS only to if any cloud provider is set. We also added the check for `InternalAddress` being empty.

Provide IP for kube-proxy if cloudprovider is set

---

cluster/plan.go

Earlier we checked for AlwaysPullImages only if PodSecurityPolicy
is true clause, need both checks separately.
https://github.com/rancher/rke/issues/1690

fix applying AlwaysPullImages to commandArgs

---

cluster/certificates.go
cluster/plan.go
cluster/reconcile.go
go.mod
go.sum
hosts/hosts.go
pki/constants.go
pki/deploy.go
pki/pki.go
pki/services.go
pki/util.go
services/etcd.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
vendor/modules.txt

* Moved stripping CA key from `GenerateRKENodeCerts` to `DeployCertificatesOnPlaneHost` because we use `GenerateRKENodeCerts` in Rancher worker logic to generate the kubelet certificate and I can't do that without the CA key.
* Implemented `GetCrtNameForHost` to get certificate name as Rancher does not default nodes to have `InternalAddress` equal to `Address` when `InternalAddress` is empty (which RKE does).
* Made `DeepEqualIPsAltNames` public as it is needed in the nodeconfig comparing old vs new cert
Depends on https://github.com/rancher/types/pull/1013

Add per node kubelet server certificate

---

cluster/plan.go

https://github.com/rancher/rancher/issues/23847
Reverting the change done in this PR for Windows only - https://github.com/rancher/rke/pull/1724
@thxCode @loganhz

Revert bind mounting ipvs lib for windows since it causes failure with Windows agent

---

services/etcd.go

Requires: https://github.com/rancher/rke-tools/pull/83
Support local local and s3 snapshot removal and restore clean up through rke-tools. 
https://github.com/rancher/rancher/issues/22900

Move snapshot remove logic to rke-tools

---

cluster/cluster.go

IngressConfig fields ExtraEnvs, ExtraVolumes and ExtraVolumeMounts are k8s types.
The yaml unmarshal done in ParseConfig can't unmarshal these properly because they have
nested fields without yaml tags. This commit adds logic to unmarshal
these fields separately so all nested fields get unmarshaled too.
https://github.com/rancher/rke/issues/1104

Handle unmarshal of ingressConfig's k8s native fields separately

---

cluster/cluster.go

Forwardport: https://github.com/rancher/rke/pull/1769
IngressConfig fields ExtraEnvs, ExtraVolumes and ExtraVolumeMounts are k8s types.
The yaml unmarshal done in ParseConfig can't unmarshal these properly because they have
nested fields without yaml tags. This commit adds logic to unmarshal
these fields separately so all nested fields get unmarshaled too.

[Forwardport] Handle unmarshal of ingressConfig's k8s native fields separately

---

cluster/etcd.go
services/etcd.go

when removal is executed as a part of restoration
https://github.com/rancher/rancher/issues/24360

Correct system image for etcd snapshot removal

---

cluster/file-deployer.go

https://github.com/rancher/rke/issues/1805
Considerations taken:
- Rewrite logic to not have cloud config if there is no additional config besides configuring the cloud provider: this will affect code in more than one place, this will also affect all existing clusters as a flag removed will trigger updates on most of the k8s containers/components and should not be in a patch release.
- The file will not be removed in this logic: we dont support switching cloud provider and there is no valid use case to have it removed besides that

Deploy cloud-config file while contents are empty

---

cluster/plan.go

Change to not consider the prefixPath for the /lib/modules bind mount in the kube-proxy container. Instead always bind mount /lib/modules to /lib/modules. I'm unaware of any systems that store their modules at a different path or at a minimum provide a symlink at /lib/modules to the actual path like /usr/lib/modules in the case of RancherOS.
#1823, where the bind mount pointed to /opt/rke/lib/modules on RancherOS.

Remove the prefixPath from the /lib/modules bind mount for kube-proxy IPVS support

---

log/log.go
pki/services.go

When the parameter `generate_serving_certificate: true` is set on the cluster, rancher will regenerate kubelet certs every time worker agents connect back every ~2 mins. This is flooding the rancher logs in this case. Lowering the level to debug.
https://github.com/rancher/rancher/issues/24942

Drop the log level to Debug since rancher can call this frequently

---

pki/services.go
pki/services_test.go

Problem: 
The ETCD certs of removed hosts will not be removed or rotated. 
API/UI will always show there are certs expired in this cluster even all needed certs are rotated.
In the screenshot, the highlight etcd host has been removed from the cluster.
So users will always see the certificates expire warning in Rancher
Solution: 
Delete the unused ETCD certs when rotating certs
Related Rancher PR:
https://github.com/rancher/rancher/pull/24548
Issue: 
https://github.com/rancher/rancher/issues/24333

Fix always show certificates are about to expire issue

---

cluster/cluster.go
cluster/defaults.go
cluster/hosts.go
cluster/validation.go
cmd/up.go
k8s/node.go
services/controlplane.go
services/node_util.go
services/workerplane.go

RKE does a cluster scan to find the unreachable hosts, and if that number
is same as or exceeds maxUnavailable, upgrade won't proceed.
This commit introduces a label users can provide for their nodes so they
don't get counted as unavailable and are excluded from upgrade.
This commit also includes a couple of bug fixes:
1. When maxUnavailable was provided as a percentage, I was including only the active hosts in the calculation, whereas inactive hosts should be included too. So if from 5 worker hosts 1 is inactive and maxUnavailable is 40%, I was calculating maxUnavailable number as 40% of 4, instead of 40% of 5. Changed this to include all hosts  
2. When upgrading any node, I first check all nodes in the cluster to see if any previously upgraded hosts became inactive, I was listing them …

Accept label to ignore nodes during upgrade

---

services/controlplane.go

https://github.com/rancher/rke/issues/1909
This commit addresses the part of the above bug where controlplane hosts do not undergo upgrade but state gets saved. This is because on seeing one "NotReady" host, the error returned was using the variable for a previously defined error which could be nil, hence not returning any error

Return correct error if maxUnavailable hit for control

---

cluster/defaults.go

Currently, the "%" is interpreted as a formatting directive in DefaultMaxUnavailable.
`"No input provided for maxUnavailable, setting it to default value of %10!(NOVERB)"`

Fix formatting

---

docker/docker.go

https://github.com/rancher/rke/issues/1918
Problem: Docker error is shown as nil in log message
Root cause: err got redefined in loop and passed value was nil
Solution: do not redefine err in loop

Do not wipe the actual Docker error to show in log

---

cluster/cluster.go
cluster/plan.go
cluster/reconcile.go

it's unexpected to see empty service options, but node plan shouldn't just be generated and passed to agents in this case
https://github.com/rancher/rancher/issues/23284

[v1.0] error out if service options are not found

---

metadata/metadata.go

panic from logs
```
2020/02/28 13:36:17 [INFO] Refreshing driverMetadata in 1440 minutes
fatal error: concurrent map writes
goroutine 14406 [running]:
runtime.throw(0x4a02e62, 0x15)
/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc001a43718 sp=0xc001a436e8 pc=0x10317f2
runtime.mapassign(0x4107d60, 0xc00b28e2a0, 0xc001a43810, 0x12)
/usr/local/go/src/runtime/map.go:588 +0x5c3 fp=0xc001a437a0 sp=0xc001a43718 pc=0x1010c03
github.com/rancher/rke/metadata.initK8sRKESystemImages(0xc00ace2180, 0xc00ace3a70, 0xc00ace3aa0, 0xc00b132270, 0xc00b1322a0, 0xc00b1322d0, 0xc00b132300, 0xc00b132330, 0xc00b132510, 0xc00b132540, ...)
/Users/kshah/go/pkg/mod/github.com/rancher/rke@v1.1.0-rc8/metadata/metadata.go:129 +0x42a fp=0xc001a44368 sp=0xc001a437a0 pc=0x2c64e7a …
```

lock to avoid concurrent map writes

---

main.go

https://github.com/rancher/rancher/issues/24994
I've tried to think of a couple of ways to do this:
- Implement a loglevel flag and try to keep `--debug` and `--quiet`, and offer a new loglevel flag. But the new loglevel flag would only serve the new TRACE level, because we are not offering any per level logging. It's debug or quiet (or TRACE after this) so there is no real point in having a separate flag.
- Adding trace flag as below seems to be not bad, it's a global level flag and it is an exception to use it (TRACE will be logging everything, including sensitive info), so having a specific flag to enable it should be OK. I didn't include a shorthand for it (`-t` or `-T` because it probably gets confusing and it's not that common for people to know what `-t` is and `-T` is maybe more …

Add flag to enable TRACE logging

---

cluster/state.go

This PR corrects the log output during `rke up`.
The output still contains the legacy configmap name `cluster-state`. The new cluster state is saved in `full-cluster-state`.

Fix log output of full-cluster-state configmap name

---

cluster/cluster.go
cluster/reconcile.go
cluster/state.go
docker/docker.go
metadata/metadata.go
pki/deploy.go

Moves logging structs/file content to trace to keep debug readable.
Added log for `data.json` to show checksum to have a way to identify what file was retrieved/used.

Add logging structs/file content to trace loglevel

---

cluster/cluster.go
cluster/defaults.go
services/controlplane.go
services/node_util.go
services/workerplane.go

1. Compare maxUnavailable with powered off hosts before attempting to reconcile
NotReady hosts https://github.com/rancher/rancher/issues/25841
2. Include powered off hosts as failed hosts for controlplane upgrade to return error https://github.com/rancher/rancher/issues/25599
3. Change coredns upgrade strategy. With addons changes it was changed to have the k8s
default value for a deployment of 25% maxUnavailable and maxSurge. This commit changes it
back to maxUnavailable of 1 to avoid dns addon upgrade issues https://github.com/rancher/rke/issues/1944

MaxUnavailable and powered off hosts comparison

---

hosts/hosts.go
pki/services.go

https://github.com/rancher/rancher/issues/25814
Moved it to trace because Rancher calls this in the controller every node plan generation.
Created https://github.com/rancher/rke/issues/1949 to consistently use logging package

Refactor unused certificate logging

---

cmd/cert.go
cmd/etcd.go

https://github.com/rancher/rke/issues/1974
Problem: `rke cert rotate` rotates all certificates, but it rotates the kube-ca cert only if the flag 
`--rotate-ca` is used. RKE rotates certs even if kube-ca has expired, and expired kube-ca shouldn't be generating certs. 
Solution: RKE shouldn't rotate certs if `--rotate-ca` is not passed to `rke cert rotate` without checking the expiration of kube-ca

Validate kube-ca cert before rotating certs

---

cluster/defaults.go

We reset dns fields if provider isn't set, and that's removing nodelocal config too.
https://github.com/rancher/rke/issues/2014
Backporting https://github.com/rancher/rke/pull/1962 will prevent it

[Backport] Retain user-configured dnsConfig fields when provider is not set

---

addons/addons.go
cluster/addons.go
templates/addonjob.go

https://github.com/rancher/rke/issues/1916
This implements similar logic to configuring `provider: none` to monitoring/ingress, if there are no addons defined, check for the addon job and remove it. The logic that needed changing was that `-o name` provides you with `<kind>/<name>` which works for `kubectl delete` but it doesn't include namespace so resources in the non-default namespace (which is `kube-system`) were not removed.
Example:
When deleting the `ingress` addon, the output of the command how it is today is:
```
kubectl get -f ingress.yaml -o name
namespace/ingress-nginx
configmap/nginx-configuration
configmap/tcp-services
configmap/udp-services
serviceaccount/nginx-ingress-serviceaccount
clusterrole.rbac.authorization.k8s.io/nginx-ingress-clusterrole …
```

Remove user addons when not present

---

docker/docker.go
docker/docker_test.go

Docker auth is currently generated using the base 64 URL encoding - switch to standard encoding, as expected by docker.
Fixes https://github.com/rancher/rancher/issues/27029

Use standard base64 encoding for Docker auth

---

docker/docker.go
docker/docker_test.go

Backport of https://github.com/rancher/rke/pull/2052
https://github.com/rancher/rancher/issues/27029

[1.1] Use standard base64 encoding for Docker auth

---

cluster/cluster.go
cluster/defaults.go

This reverts commit 763a896380c318fbef1825788e50528873c9976a.
(cherry picked from commit 6e194ab1a620182a10d32425b9c48dd9e2552b25)
Note:
don't need the other revert commit about rke version dev since already updated it to `1.1.2-rc0`

Revert "Add support for k8s 1.18"

---

templates/nginx-ingress.go

ingress daemonset in rke `0.2.10` had `apiVersion=extensions/v1beta1`
which defaults to `onDelete` strategy. We change apiVersion in new
template to `apps/v1`, but without explicitly changing the strategy,
it stays `onDelete`.
https://github.com/rancher/rancher/issues/27354

[0.2] set updateStrategy for nginx-ingress

---

services/node_util.go

https://github.com/rancher/rancher/issues/27618
IgnoreDaemonSets was changed to be a pointer field, and when getting its value DrainInput wasn't set causing the panic. This PR adds a check for DrainInput

Check drainInput for nil to avoid panic

---

services/node_util.go

https://github.com/rancher/rancher/issues/27618
IgnoreDaemonSets was made a pointer for some terraform changes, and panics when it's not checked for nil before dereferencing

[2.4] Check ignoreDaemonsets for nil to avoid panic

---

services/node_util.go

https://github.com/rancher/rancher/issues/27618
IgnoreDaemonSets was made a pointer for some terraform changes, and panics when it's not checked for nil before dereferencing

Check ignoreDaemonsets for nil to avoid panic

---

cmd/etcd.go

Before this change, `rke etcd snapshot-restore` did not support `--custom-certs` and `--cert-dir` flags. As a result, an attempt to restore snapshot on cluster using custom certificates resulted in fatal error:
```
FATA[0032] CA Certificate or Key is empty
```
This commit adds `--custom-certs` and `--cert-dir` flag handling similar to `rke up` command, resolving the issue.

Fix restoring backups when custom certs are used

---

cluster/etcd.go
cluster/state.go
cmd/etcd.go
docker/docker.go
pki/constants.go
pki/deploy.go
services/etcd.go
services/services.go

In combination with https://github.com/rancher/rke-tools/pull/100
How this works for saving etcd snapshots:
- Added step that deploys the statefile
- In rke-tools, it will check if there is a state file present, and if yes, it will be included in the snapshot
How this works for restoring etcd snapshots:
- Setup a temporary cluster to create dialers to the nodes (because we dont have the state file)
- Try to extract the state file from the snapshot and read it
- If found, write it locally and use it to restore
- If not found, fall back to the local state file
Most of the decisions are token to keep backwards compatibility, mainly the steps of rke-tools checking if the state file is present, so even when newer versions are used, it will still successfully create a snapshot. For restoring, …

Able to include and extract state file in snapshot

---

docker/docker.go
docker/docker_test.go

Backport #2052
Original Issue - rancher/rancher#27029
Backport Issue - https://github.com/rancher/rancher/issues/28004

[v1.0] Use standard base64 encoding for Docker auth

---

cluster/defaults.go
cluster/state.go
cmd/cert.go
cmd/encryption.go
cmd/etcd.go
cmd/remove.go
cmd/up.go

https://github.com/rancher/rke/issues/1336
This adds the flag `--use-local-state` for the `rke etcd restore-snapshot` command to use the local statefile and not check the snapshot archive for an included statefile

Add restore flag to use local state

---

cmd/etcd.go

Backport of https://github.com/rancher/rke/pull/1957
This also includes a cherry-pick fix of the local-state-flag for etcd snapshot-restore

[release/v1.1] Fix restoring backups when custom certs are used

---

Dockerfile.dapper

Similar to `rancher/rancher`: https://github.com/rancher/rancher/pull/28301/commits/403db42718f3eb0191e9ea81dbfc2e858876ddbf

Update to Go 1.14.7

---

cluster/cluster.go
util/util.go

Since filepath.Clean() is being called in the rancher master it'll always be in Linux, had to write a quick cleaner to use.

added windows path cleaner

---

cluster/plan.go

https://github.com/rancher/rke/issues/2194
As this logic went, it would relabel /lib/modules, except on enterprise
linux and when SELinux is enabled (even just permisive).
Flatcar Container Linux defaults to SELinux on, but permisive, and
`/lib/modules/` is a symlink to the read-only `/usr`.
So `./rke up` would fail on attempting to relabel /usr.
The prior work around is to set `SELINUX=disable` in
/etc/selinux/config.
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>

cluster/plan: don't relabel /lib/modules by default

---

cluster/defaults.go

While the types were added, the actual default logic was missing which led to the network plugin not being able to deploy when using CanalControllers.
https://github.com/rancher/rancher/issues/26717
Signed-off-by: Chris Kim <oats87g@gmail.com>

Add CanalControllers to the systemImagesDefaultsMap

---

hosts/hosts.go

From docker info:
```
Operating System: Flatcar Container Linux by Kinvolk 2513.3.0 (Oklo)
```
to ensure host path is `/opt/rke`

hosts: mapping Flatcar from the docker host info

---

k8s/node.go

When cloud provider is configured, the node name can be set by the cloud provider. If we don't account for this, the node cannot be found when we do cluster operation (for example, node delete)
https://github.com/rancher/rke/issues/2122

Use node label when cloudprovider is configured

---

types/rke_types.go

This reverts commit 998c4fd72db63cc3ba15e5931cee3675e1fad47c.
This changes the type of ignoreDaemonSets from *bool to bool, which was required for terraform.

Revert "set ignoreDaemonsets field as nonnullable"

---

dind/dind.go
scripts/integration

This is to avoid issues where provisioning succeeds (`rke up`), which means the components can be deployed using Docker and needed manifests are technically valid but the resources are not getting ready/healthy. Although this is something we should look at in improving in RKE, the first step is to make sure PRs won't go in which break cluster from becoming healthy (for example, changing system images without supporting templates)

Check rollout status in integration test

---

cluster/plan.go

https://github.com/rancher/rke/issues/2266
As this logic went, it would relabel /lib/modules, except on enterprise
linux and when SELinux is enabled (even just permisive).
Flatcar Container Linux defaults to SELinux on, but permisive, and
`/lib/modules/` is a symlink to the read-only `/usr`.
So `./rke up` would fail on attempting to relabel /usr.
The prior work around is to set `SELINUX=disable` in
/etc/selinux/config.
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>

[release/v1.1] cluster/plan: don't relabel /lib/modules by default

---

scripts/integration

This adds testing of upgrading clusters in CI. For initially provisioning clusters, we use a variable called `$all_versions` with all the versions available in the built RKE CLI. The logic is to grep for the next version in that list to upgrade to, so in case of the following available versions: `"v1.16.15-rancher1-2 v1.17.12-rancher1-1 v1.18.9-rancher1-1 v1.19.2-rancher1-1"` we will attempt to upgrade:
- cluster v1.16.15-rancher1-2 to v1.17.12-rancher1-1
- cluster v1.17.12-rancher1-1 to  v1.18.9-rancher1-1
- cluster v1.18.9-rancher1-1 to v1.19.2-rancher1-1
In case no new version is found (in this case for v1.19.2-rancher1-1), we skip.
Output from cluster provisioning
```
2020-09-26T08:14:26Z ---- TEST RESULTS ----
--
1156 | 2020-09-26T08:14:26Z [PASS] v1.17.12-rancher1-1
1157 | …
```

Add upgrade tests to integration

---

scripts/integration

Backport of https://github.com/rancher/rke/pull/2253
This adds a clear kubectl cache action to avoid issues with API deprecations

[release/v1.1] Add upgrade tests to integration

---

cluster/defaults.go
services/controlplane.go
services/workerplane.go
types/rke_types.go

rancher/rancher#29058
rancher/terraform-provider-rancher2#440
Allow the drain flag on the NodeUpdateStrategy struct to be nil instead of defaulting to false.

updated NodeUpgradeStrategy.Drain to use a pointer

---

cluster/addons.go
cluster/cluster.go
cluster/defaults.go
cluster/validation.go
types/rke_types.go

Minor tweak to allow addons.go to process the new fields introduced in IngressConfig for http and https ports to be passed to the nginx-ingress template available in kdm.
Related to issue: #1876

Allow addons.go to parse http and https ports for ingress controller

---

cluster/cluster.go
cluster/defaults.go

Problem:
Setting defaults for ingress in parse logic works only for
rke standalone but not when rancher calls rke using ClusterUp.
Solution:
Setting them during the cluster defaults logic
https://github.com/rancher/rancher/issues/29745

set default ingress network mode for both rancher and rke

---

cluster/cluster.go
cluster/defaults.go

Forwardport of https://github.com/rancher/rke/pull/2297
https://github.com/rancher/rancher/issues/29745
Problem:
Setting defaults for ingress in parse logic works only for
rke standalone but not when rancher calls rke using ClusterUp.
Solution:
Setting them during the cluster defaults logic

[release/v1.2] set default ingress network mode for both rancher and rke

---

README.md
main.go

https://github.com/rancher/rke/issues/2350
Other commit is to remove `latest` from the URL in the warning when using non official releases.

Release info

---

main.go

Backport of https://github.com/rancher/rke/pull/2351

[release/v1.2] Remove latest from rke releases URL in warning

---

main.go

Backport of https://github.com/rancher/rke/pull/2351

[release/v1.1] Remove latest from rke releases URL in warning

---

cluster/cluster.go
metadata/metadata.go

Problem:
We need to wait for initMetadata to complete before reading map values and that is confirmed only by nil map check. Another initCluster call could wrongly assume metadata is initialized completely and result into concurrent read and write map panic.
https://github.com/rancher/rancher/issues/30224

[v1.2] wait for kdm metadata to be initialized

---

cluster/cluster.go
metadata/metadata.go

Problem:
We need to wait for initMetadata to complete before reading map values
and that is confirmed only by nil map check. Another initCluster call
could wrongly assume metadata is initialized completely and result into
concurrent read and write map panic.
https://github.com/rancher/rancher/issues/30224
Backport https://github.com/rancher/rke/pull/2354

[v1.1] wait for kdm metadata to be initialized

---

cluster/addons.go
cluster/defaults.go
k8s/deployment.go
k8s/service.go
types/rke_types.go
types/zz_generated_deepcopy.go

Set default http backend to be optional for ingress nginx. It will be enabled by default.
Relevant Issue: https://github.com/rancher/rancher/issues/25590
Relevant Comment: https://github.com/rancher/rancher/issues/25590#issuecomment-729248564
KDM Data PR: https://github.com/rancher/kontainer-driver-metadata/pull/425

Set default http backend to be optional

---

cluster/encryption.go
cmd/encryption.go
cmd/up.go
log/log.go
types/rke_types.go
vendor/k8s.io/client-go/util/retry/OWNERS
vendor/k8s.io/client-go/util/retry/util.go
vendor/modules.txt

These changes do the following:
* Early return from ClusterUp if key rotation is detected 
- Enables an API action from Rancher to trigger the key rotation
* Improved logging during secrets rewrite process
- Log messages of the form `[rewrite-secrets] X secrets rewritten` where X is a multiple of 50, e.g. 50, 100, 150, etc
* Get secrets in batches (instead of single call) to avoid client timeout issues for large secret sets, and perform incremental rewrites
- This PR changes it so that each batch is retrieved and rewritten before proceeding to the next. This guarantees we are never holding more than `<secretBatchSize>` secrets in memory at any given point in time
- The case of the continue token expiring is also handled by having the rewrite process restart the list operation. If this …

Encryption Key Rotation Changes

---

cluster/addons.go
cluster/defaults.go
k8s/deployment.go
k8s/service.go
types/rke_types.go
types/zz_generated_deepcopy.go

Set default http backend to be optional for ingress nginx. It will be
enabled by default.
Backport of PR: https://github.com/rancher/rke/pull/2346

[1.2] Set default http backend to be optional

---

cluster/cluster.go
cluster/encryption.go

Additional logging has been requested by QA for the rewrite operation.
Reducing the number of workers helps mitigates some request throttling.
Issues: 
- rancher/rancher#28753
- rancher/rancher#30541

[1.2] Key Rotation - Enhance Logging, Reduce Workers

---

types/image/mirror.go

https://github.com/rancher/rancher/issues/30840
This removes `noiro` (Cisco ACI) prefixed images from the `rancher-images.txt` artifact on release.

Exclude Cisco ACI image from mirror

---

cmd/config.go

Fixed a small typo in `config.go` at:
```
const (
comments = `# If you intened to deploy Kubernetes in an air-gapped environment,
)
```
to:
```
const (
comments = `# If you intended to deploy Kubernetes in an air-gapped environment,
)
```

EL - Fix a typo in config.go

---

README.md

fixed typo in `RANCHER_METADATA_URL`

Update README.md to fix typo in RANCHER_METADATA_URL

---

cluster/defaults.go
cluster/etcd.go
docker/docker.go
go.mod
go.sum
vendor/github.com/rancher/types/apis/management.cattle.io/v3/backup_types.go
vendor/modules.txt

Issue https://github.com/rancher/rancher/issues/30663
Requires https://github.com/rancher/types/pull/1196 : `Timeout` field has been added to `Services.Etcd. BackupConfig`. Once types PR is merged, this PR should be updated to use it.
Required by https://github.com/rancher/rancher/pull/30885
This PR adds the feature to set etcd snapshot timeout instead of the [default](https://github.com/rancher/rke/blob/v1.1.6/docker/docker.go#L495). 
To limit the changes at the rke logic and functions parameters, the `Services.Etcd. BackupConfig.Timeout` field is read at `cluster. SnapshotEtcd` and `cluster.RestoreEtcdSnapshot` functions, using execution context to propagate the argument. `docker.WaitForContainer` function has been modified to set default `WaitTimeout=300` or timeout provided by context …

[v1.1] Added etcd snapshot timeout parameter

---

cmd/etcd.go

https://github.com/rancher/rke/issues/1501
Adds a warning when the snapshot name provided contains the file extension while it should be the snapshot name without file extension

Warn when snapshot name contains file extension

---

cluster/state.go
pki/deploy.go

https://github.com/rancher/rke/issues/2395
Besides kubeconfig, this also changes rkestate to be written as 0600 instead of 0640

Write kubeconfig/state with stricter permission

---

pki/util.go

Users leveraging custom certs directories face errors when deploying
if the directory contains any files that do not end in .pem. This
change adds additional validation to ensure files are *.pem before
attempting further logic.
Signed-off-by: Alexander Hughes <Alexander.Hughes@pm.me>

Update cert filename validation to *.pem

---

cluster/plan.go

This allows for mixed-architecture etcd clusters.

Use the node's architecture to build etcd process

---

cluster/cluster.go
types/rke_types.go
util/util.go

https://github.com/rancher/rke/issues/2525
Hello ! i use RKE command line for production cluster, all works fine, thanks a lot for this product !
For development and testing purpose, i use terraform RKE provider (based on rke lib) through an SSH bastion and i use terraform Kubernetes provider through a SOCKS proxy with HTTPS_PROXY env var.
But, when rke create the rke-job-deployer ServiceAccount, the k8s client use local http proxy env vars through the SSH tunnel on the bastion, and cannot connect to the kubernetes controlplane.
```
terraform apply
...
module.k8s-full-stack.module.k8s_cluster.rke_cluster.cluster: Still creating... [3m40s elapsed]
Error: 
============= RKE outputs ==============
...
time="2021-04-19T11:15:38+02:00" level=info msg="[controlplane] Successfully started …
```

Unset proxy env vars when using bastion

---

.dockerignore
.drone.yml
dind/dind.go
scripts/integration

This runs in parallel with current CI to save time (else every CNI needs to be tested sequentially). The "downside" of this is that we need to build the binary again.
This will make testing new CNI and upgrades better as we now test each CNI + upgrades. This came up after updating addons for k8s v1.21.
This also adds `kubectl` output to each cluster provisioning + upgrade so you can check what images have been used in the test (to verify versions).

Test all CNI in CI

---

cluster/plan.go

controller manager must start with proper authorization and authentication kubeconfig in args starting 1.22. k8s 1.22 has
disabled insecure serving for kube controller manager. https://github.com/kubernetes/kubernetes/pull/96216 
insecure serving for kube scheduler is going to be disabled starting 1.24, so updating the args for it too. 
https://github.com/kubernetes/kubernetes/pull/102857
Related Issue: https://github.com/rancher/rancher/issues/35751

add extra args for 1.22

---

cmd/encryption.go
cmd/up.go

**Issue**: https://github.com/rancher/rke/issues/2840
**Problem**:
RKE will panic if we enable rotate_encryption_key but disable secrets_encryption_config when creating a cluster. The panic happens because RKE tries to use the rkeConfig, which does not exist. The rkeConfig will be made after the rke up command succeeds.
**Solution**:
Skip the rotateEncryptionKey operation when creating a new cluster. Also, In this case, keys are just made for the first time, so there is no need to rotate them.
**Tests**:
run `rke up` with the following cluster.yml
```
nodes:
- address:  xxx
internal_address: xxx
user: ubuntu
role: [controlplane,worker,etcd]
ssh_key_path: xxx
rotate_encryption_key: true
```
Related Rancher Issue: https://github.com/rancher/rancher/issues/36333

Prevent  a panic if we enable rotate_encryption_key but disable secrets_encryption_config when creating a cluster

---

.drone.yml
scripts/create-releasenote.sh
scripts/package

This adds a release note with includes k8s versions similar to Rancher: https://github.com/rancher/rancher/blob/release/v2.6/.drone.yml#L311

[release/v1.3] Add pre release notes with k8s versions included

---

scripts/integration

Previous RCs had a default k8s version set that was not in the all supported versions for that RC, for example:
All versions when running `rke config -l -a`:
- v1.19.2-rancher1-1
- v1.20.3-rancher1-2
- v1.21.4-rancher1-1
- v1.22.6-rancher1-2
Default version when running `rke config -l`:
- v1.22.6-rancher1-1
This is caught with this PR and the build exits with code 1.

[release/v1.3] Check if default k8s version is among all versions

---

cluster/addons.go

Fixes: https://github.com/rancher/rancher/issues/36985
For every user addon, rke runs an `rke-user-addon-deploy-job` job, which applies the user add-on configs to the cluster. Although when the cluster version gets updated, the user addon needs to be re-applied.
Currently if the user addons are previously applied, they get ignored subsequently, even if the k8s version is being upgraded. Hence, this PR changes that behavior to force-apply the user addons for each `rke up` command run. This will make sure that even if the k8s version of the cluster is upgraded, the user addon changes do not get lost.

Add logic to fix coreDNS add-on config issue while cluster upgrade

---

cluster/plan.go
hosts/hosts.go
types/rke_types.go
types/zz_generated_deepcopy.go

Issue: https://github.com/rancher/rancher/issues/25500
When setting up [service account token volume projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) within the cluster.yaml, users were not able to specify a flag multiple times with different values within the `ExtraArgs` section of the `kubeapi` service. This prevents users from specifying multiple `service-account-key-file`’s, multiple `service-account-issuer`’s, or multiple `api-audiences`. This issue may also exist for the other services, and is not specific to service account projection (although that is the requested usecase)
In an effort to preserve backwards compatibility, two new fields have been added to the `BaseService`: …

Add fields `ExtraArgsArray` and `WindowsExtraArgsArray`

---

.drone.yml
scripts/dispatch

This enables to dispatch the workflow in rancher/rancher to run `go get` on the newly created tag in RKE and create a PR with the changes.

[release/v1.3] Add workflow to create PR in Rancher on tag

---

metadata/metadata.go

Using Rancher version 2.4.3.
Large installation with 100+ clusters and 10+ cattle-servers pods in HA mode.
There's panic at concurrent read-write access to K8sVersionToRKESystemImages map:
```
Mar 9, 2022 @ 11:48:46.568 fatal error: concurrent map read and map write
Mar 9, 2022 @ 11:48:46.574 github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster.(*Cluster).setClusterImageDefaults(0xc075c1e000, 0x20, 0xc070913580)
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/rke/cluster/defaults.go:433 +0x86 fp=0xc13711c188 sp=0xc13711b968 pc=0x22f5426
```
Seems map reading is happening at the same time as updating map.
The only place where it is modified is in rke/metadata/metadata.go.
This PR avoids map update by substituting map.

Fix panic at updating K8sVersionToRKESystemImages

---

cluster/plan.go

Add bind `/var/lib/kubelet/config.json:/.docker/config.json`
Pod creation failing with following error when using private registry: 
`
E0801 21:49:55.450436    6271 kuberuntime_manager.go:815] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed pulling image \"ec2-3-144-97-102.us-east-2.compute.amazonaws.com/rancher/mirrored-pause:3.6\": Error response from daemon: Get https://ec2-3-144-97-102.us-east-2.compute.amazonaws.com/v2/rancher/mirrored-pause/manifests/3.6: no basic auth credentials" pod="kube-system/rke-network-plugin-deploy-job-92w6t"
`
https://github.com/rancher/rancher/issues/38473
RKE stores docker config at `/var/lib/kubelet/config.json` (https://github.com/rancher/rke-tools/blob/master/entrypoint.sh#L75) , but the external cri-dockerd relies on …

bind rke kubelet docker config path to default docker config path

---

cluster/plan.go

Issue: https://github.com/rancher/rancher/issues/38564
The `cluster-dns` argument was left behind after creating the command arguments for the `kubelet`. This PR changes the ordering so that the argument is persisted after calling `appendArgs`.

Ensure NodeLocal.IPaddress is passed when creating CommandArgs

---

cluster/addons.go
k8s/job.go

**Problem:** 
With https://github.com/rancher/rke/pull/2900/files, we were deleting user addons during deploy. This causes problems if user config has namespaces like `cattle-system` or other resources which break the cluster provisioning. 
**Solution:** 
Don't delete all user resources and always rerun the job if addon or addonInclude fields are set for https://github.com/rancher/rancher/issues/38749. The job reruns kubectl apply and redeploys the user addon config after system addons are run, so it retains the user config for issues like https://github.com/rancher/rancher/issues/38703. 
**Testing:** 
- Deployed RKE1 clusters with user addon config linked in both issues mentioned above and tested the cluster upgrades successfully + retains the config.

update user addon logic to delete job, not addons

---

cluster/validation.go

This commit fixes a typo that causes that HTTPS ingress port is not validated correctly.

Fix ingress' HTTPS port validation

---

metadata/metadata.go

Issue: https://github.com/rancher/rancher/issues/39239
we need to bump the rke dev version to "v1.4.99" so that RKE can calculate the version list properly. 
-------
~Dot Not Meger - need the [KDM PR](https://github.com/rancher/kontainer-driver-metadata/pull/987) merged first~
KDM changes have been merged into the base branch

[release/v1.4]  update rke dev version

---

types/rke_types.go

Issue: https://github.com/rancher/rancher/issues/26955
Backport for:  https://github.com/rancher/rke/issues/2611
This is a back-port PR which introduces the `tags` field to the Azure Cloud Provider for RKE 1.3.x

Add `tags` field to the Azure cloud provider

---

cluster/defaults.go

required the PR: https://github.com/rancher/rke/pull/3086 to be merged first since CI is likely to fail because of kdm data.json being out of sync.
fix for issue: https://github.com/rancher/rancher/issues/37461

check for empty update strategy while setting default values for dns addon deployment

---

pki/cert/cert.go

Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

[release/v1.4] Use constant instead of value for cert duration

---

.github/workflows/update-readme.yml

As seen in https://github.com/rancher/rke/pull/3111, the `wget` is not sufficient to get enough tags to list the latest for v1.2.x. This changes the logic to use the included GitHub CLI to retrieve releases and filter on that output.
Tested in https://github.com/sebtestorg2/actions-test/actions/runs/3572161876, resulting PR https://github.com/sebtestorg2/actions-test/pull/134/files

[release/v1.4] Improve getting releases/tags when updating README

---

cluster/defaults.go
cluster/network.go
types/rke_types.go

Back port of https://github.com/rancher/rke/pull/3039

Backport: added variables for ACI-CNI 5.2.3.4

---

cluster/validation.go
k8s/psp.go

Issue https://github.com/rancher/rancher/issues/40652
This PR drops the checks for PSP resources in the cluster.
Here is the original PR for adding such checks : https://github.com/rancher/rke/pull/3132

drop the checks for PSP resources in the cluster

---

codegen/codegen.go

`go generate` did not result in a new `data.json`, likely due to the recent RC that was cut ~1 week ago. Running a diff against the `data.json` in the repository and the one from `releases.rancher.com` shows that they match

[v1.4.4] Switch to release-2.7

---

cluster/defaults.go
cluster/hosts.go

https://github.com/rancher/rke/issues/3247
https://github.com/rancher/rancher/issues/41292
The issue is reported in Rancher at first, but the root cause is in RKE. 
When RKE initializes the cluster, it sets the default value to the field `spec.Services.KubeAPI.PodSecurityConfiguration` when no value is provided in the cluster.yml file (see [code](https://github.com/rancher/rke/blob/5d360491203a3c1511aa6d12c496679dea05ba37/cluster/defaults.go#L398-L400)) **regardless of the cluster's Kubernetes version**.
But later on, when RKE validates the cluster's configuration before starting the upgrading, it expects to see the abovementioned field to be set only for clusters whose k8s version is **at least 1.23** (see [code](https://github.com/rancher/rke/blob/5d360491203a3c1511aa6d12c496679dea05ba37 …

set the default PodSecurityConfiguration value only if the cluster's k8s version is at least 1.23

---

codegen/codegen.go

There are no data.json changes in this PR due to https://github.com/rancher/rke/pull/3283, which generated the file ~2 hours ago and matches the contents in the KDM repo. This PR just swaps the KDM url to release-v2.7

KDM Out Of Band Update For June 2023 - Rancher v2.7

---

cluster/defaults.go
cluster/hosts.go

GH issue https://github.com/rancher/rancher/issues/42127
Backport of the PR https://github.com/rancher/rke/pull/3291

[Backport] Set the default PodSecurityConfiguration value only if the cluster's k8s version is at least 1.23

---

services/etcd.go

While working on documentation, I found this log line that uses the `etcd-snapshot-once` container name incorrectly as the code for running it once is in the part above and is returned. See log lines for how it is currently below, where the container name is different between the info and the debug log line.
```
time="2023-08-02T20:01:01+02:00" level=info msg="[etcd] Running rolling snapshot container [etcd-snapshot-once] on host [52.13.57.129]"
time="2023-08-02T20:01:01+02:00" level=debug msg="[etcd] Using command [/opt/rke-tools/rke-etcd-backup etcd-backup save --cacert /etc/kubernetes/ssl/kube-ca.pem --cert /etc/kubernetes/ssl/kube-node.pem --key /etc/kubernetes/ssl/kube-node-key.pem --name etcd-rolling-snapshots --endpoints=172.26.14.216:2379 --retention=72h --creation=12h] for …
```

Use correct container name in log

---

cluster/addons.go
cluster/state.go
cmd/common.go
cmd/config.go
codegen/codegen.go
docker/docker.go
hosts/tunnel.go
main.go
metadata/metadata.go
pki/cert/io.go
pki/deploy.go
pki/util.go
services/etcd_util.go
services/healthcheck.go
util/util.go

This PR removes the deprecated io/ioutil and replaces its calls with the recommended ones (mostly in os library)
WARNING
Code generated by go-bindata will still use `ioutil` because go-bindata is that old

Replace deprecated io/ioutil

---

.github/workflows/update-readme.yml

- RKE 1.2/Rancher 2.5 is EOL, remove from README-template
- RKE 1.5 is upcoming but needs conditional as it is not out yet and we don't want lines without a release

Remove 1.2 and add 1.5 to README template

---

codegen/codegen.go

Running `go generate ./...` did not result in any changes

switch to release-v2.7 for RKE v1.4.10 release

---

go.mod

Replace some k8s modules with specific versions to get rid of the "unknown revision v0.0.0" error caused by the k8s.io/kubernetes module
Upstream Issue: https://github.com/kubernetes/kubernetes/issues/79384

Fix "unknown revision v0.0.0" error caused by the k8s.io/kubernetes module

---

.drone.yml

* The package folder was removed while moving to BCI in PR #3368, but the same is still used in the `stage-binaries` step of the Drone CI configuration, which is causing the tag release CI to [fail](https://drone-publish.rancher.io/rancher/rke/1789/1/3) 
* Removed the `stage-binaries` step as we move to BCI, the package folder, and in turn, the `stage-binaries` step is not required anymore.

In continuation to PR #3368, remove `stage-binaries` step in Drone CI

---

scripts/dispatch

* A dispatch PR in [rancher/rancher](https://github.com/rancher/rancher) is not triggered when a new release tag is created for the `v1.5.x` version.
* Add support for `v1.5` and branch `release/v2.8` in dispatch script.

Add support for `v1.5` and branch `release/v2.8`

---

cluster/etcd.go
cluster/etcd_test.go

issue: https://github.com/rancher/rke/issues/3382
since etcd is moved to distroless base image from v3.5.7  so **/bin/sh, mv and rm**  tools will not be present in etcd Image. which is required by the restore command. [ref](https://github.com/rancher/rke/blob/d2b01281f33970e5980d307935474dac6a9833cd/services/etcd.go#L652-L670) 
One solution for that is to use a custom image which has etcdctl as well as these other required tools.
Since in rke we use rke-tools image to create etcd snapshots, i have changed restore image to rke-tools as well. since rke-tools has etcdctl with the other required deps for that command.

changed etcd restore image to rke-tools for etcd >=3.5.7

---

cluster/addons.go
cluster/cluster.go
cluster/remove.go
hosts/hosts.go
k8s/node.go
services/controlplane.go
services/node_util.go
services/workerplane.go

Problem: 
Current logic of matching `Hostname` with node name doesn't work, it is true for all nodes and we won't have always the correct hostname (set by cloud provider) under `hostname-override` in the cluster config.
Fix: 
Searching node by `InternalIP` because `ExternalIP` is populated by cloud provider in `node.Status.Addresses` after aws cloud controller manager is deployed. 
Issue: 
https://github.com/rancher/rancher/issues/43624

Fix node lookup for external aws

---

.drone.yml
.droneignore
scripts/integration-ci

https://github.com/rancher/rke/issues/3396
- Adds a `skipfiles` step taken from [rke2](https://github.com/rancher/rke2/blob/0f71c9a47b030bf152d541db52e85f05e2473ced/.drone.yml#L14), which will skip the pipeline if only non code changes are present (exitcode 78 skips the whole pipeline in Drone)
- Removes running `script/integration` in `scripts/ci`, adds `scripts/integration-ci` to be run as a separate step. This makes it possible to have it run on PR but not on tag.
- Removes all the other integration steps on tag as well, tagging is confirming an existing good state so we don't have to waste time and resources when cutting a tag.

Clean/speed up Drone

---

.drone.yml
Dockerfile.dapper
dind/dind.go
package/Dockerfile
scripts/package
scripts/test

- Moves to BCI for building
- Bumps docker-dind image used for testing
- Removes creating a Docker image for RKE as we are not publishing/using it
- Removes the race flag for testing as it requires an additional package in BCI and we don't use it anywhere else, if we would like to keep it, we can add the package (which then need to be kept up-to-date as well when we bump Go)
This also prepares the repository so we can keep it up-to-date automatically with Renovate in the future.
We can also postpone this PR to 1.5.x if wanted.

[release/v1.4] Move to BCI

---

cluster/etcd.go
cluster/etcd_test.go

issue: https://github.com/rancher/rke/issues/3485 / https://github.com/rancher/rancher/issues/44219
since etcd is moved to distroless base image from v3.5.7 so /bin/sh, mv and rm tools will not be present in etcd Image. which is required by the restore command. [ref](https://github.com/rancher/rke/blob/d2b01281f33970e5980d307935474dac6a9833cd/services/etcd.go#L652-L670)
One solution for that is to use a custom image which has etcdctl as well as these other required tools.
Since in rke we use rke-tools image to create etcd snapshots, i have changed restore image to rke-tools as well. since rke-tools has etcdctl with the other required deps for that command.
cherry-pick of https://github.com/rancher/rke/pull/3390

[v1.4.14] changed etcd restoreImage to rke-tools for etcd >=3.5.7

---

cluster/etcd.go
cluster/etcd_test.go

issue: https://github.com/rancher/rke/issues/3485 / https://github.com/rancher/rancher/issues/44218
since etcd is moved to distroless base image from v3.5.7 so /bin/sh, mv and rm tools will not be present in etcd Image. which is required by the restore command. [ref](https://github.com/rancher/rke/blob/d2b01281f33970e5980d307935474dac6a9833cd/services/etcd.go#L652-L670)
One solution for that is to use a custom image which has etcdctl as well as these other required tools.
Since in rke we use rke-tools image to create etcd snapshots, i have changed restore image to rke-tools as well. since rke-tools has etcdctl with the other required deps for that command.
cherry-pick of https://github.com/rancher/rke/pull/3390

[v1.4] changed etcd restoreImage to rke-tools for etcd >=3.5.7

---

codegen/codegen.go

Pointing to KDM release url in preparation for release.
`go generate ./...` did not modify any files when ran.

Point KDM at release URL for release

---

cluster/cluster.go

fix the bug where the value of delete_local_data is dropped by the ghodssyaml.Marshal function due to the same field has different names in YAML tag and JSON tag
https://github.com/rancher/rke/issues/3412
https://github.com/rancher/rancher/issues/44564
In the declaration of the type `NodeDrainInput` ([here](https://github.com/rancher/rke/blob/dbf3a46c7cc2e56f5a62d3a22c0bc1aca40b0da6/types/rke_types.go#L1062-L1076)), the name of the same field is different in the YAML format v.s. JSON format:
- ignore_daemonsets v.s. ignoreDaemonSets
- delete_local_data v.s. deleteLocalData
- grace_period v.s gracePeriod
In the [function parseNodeDrainInput](https://github.com/rancher/rke/blob/release/v1.5/cluster/cluster.go#L647),  RKE uses `ghodssyaml.Unmarshal` and `ghodssyaml.Marshal` to covert the …

fix the bug that delete_local_data is dropped 

---

cluster/plan.go
cluster/reconcile.go
cmd/up.go

In Rancher, enabling/changing PSACT on an RKE1 node-driver cluster doesn't restart the `kube-apiserver` container in all Control Plane Nodes.
The root cause is that RKE does not handle the restarting of the `kube-apiserver` container when the admission configuration file is changed properly: the current implementation restarts the container in only one of the CP nodes. 
This PR fixes the issue that kube-apiserver does not restart in all CP nodes after changing the Pod Security Admission Configuration.
Now, a new environment variable RKE_ADMISSION_CONFIG_CHECKSUM whose value is the checksum of the content of the admission configuration file is added to the env list that is set in the `kube-apiserver` container configuration, so any changes in the admission configuration file will result in …

Restart kube-apiserver in all CP nodes after changing the Pod Security Admission Configuration

---

codegen/codegen.go

switch KDM branch to release-v2.8
`go generate` does not generate any changes because [this PR](https://github.com/rancher/rke/pull/3541) has been merged

[v1.5] switch KDM branch to release-v2.8

---

codegen/codegen.go

`go generate .` does not produce any changes

[1.5.8] Switch KDM to the release channel 

---

go.mod
services/etcd.go

https://github.com/rancher/rke/issues/3570
https://github.com/rancher/rancher/issues/45309
If a member has been removed from etcd (either externally, or internally but an error was returned), RKE will continuously attempt to remove the member from etcd despite it no longer being a member.

check if etcd member in list before removal

---

cluster/plan.go
cluster/plan_test.go
scripts/integration

https://github.com/rancher/rke/issues/3587
https://github.com/rancher/rancher/issues/45645
Problem:
Previously, we declared the Env slice with the size of the `c.Services.KubeAPI.ExtraEnv` field, which leads to empty strings at the beginning of the Env slice because we use Golang's append function to add new elements, and Docker is not happy with that. 
Fix:
We fix this issue by declaring the Env variable as an empty slice. 
We also enhance the `getUniqStringList` function to properly trim leading and trailing spaces in each element and to ignore empty strings.  
We add unit tests for  the `getUniqStringList` function  and update the integration tests. 
Dev validation:
Compile the code locally and run `rke up` succeeds with the following section in cluster.yaml file which failed before …

Avoid allocating empty strings in the Env slice

---

cluster/plan.go
cluster/plan_test.go
scripts/integration

https://github.com/rancher/rancher/issues/45656
https://github.com/rancher/rke/issues/3596
This PR is the backport of https://github.com/rancher/rke/pull/3597, please check the original PR for details.

[Bacckport] [1.5] Avoid allocating empty strings in the Env slice

---

services/etcd.go
services/etcd_util.go

Issue: https://github.com/rancher/rancher/issues/43356 
- Etcd client v3 kept retrying on member add vs v2 client used to return errors so we didn't have timeout earlier
- DialTimeout alone doesn't suffice, also need to specify client request timeout with context
- Updated to close all etcd clients as v3 client uses grpc to connect to etcd, could leave us with leaks if not closed

[v1.6] add timeout to etcd member add call

---

services/etcd.go
services/etcd_util.go

- Etcd client v3 kept retrying on member add vs v2 client used to return errors so we didn't have timeout earlier 
- DialTimeout alone doesn't suffice, also need to specify client request timeout with context
- Updated to close all etcd clients as v3 client uses grpc to connect to etcd, could leave us with leaks if not closed

[v1.5] add timeout to etcd member add

---

.github/workflows/workflow.yaml

ref issue: https://github.com/rancher/rancher/issues/46677
Example of generated sha file: https://github.com/rancher/rke/actions/runs/10383261486/job/28747832938#step:6:27

Add setup to generate and upload sha256sum file

---

.github/workflows/workflow.yaml
codegen/codegen.go
codegen/codegen_test.go

Fixing two common issues around RKE1 release process: 
1. KDM generates the `data.json` file and includes RKE2/K3s version information, which is not used by RKE1 but causes a problem for the CI. The script validates if the `data.json` is the latest version from KDM. So we end up doing additional work on the RKE1 side even if changes are made to KDM only for RKE2/K3s versions. This is especially annoying during releases, as RKE1 validation might be complete, but we could still need to tag another RC due to updates in `data.json`. We could modify the script to ignore RKE2/K3s changes but ideally, this data shouldn’t be included at all.
2. We manually update the KDM URL to `../release-v2.x/data.json` for final releases, and then switch it back to `../dev-v2.x/data.json` after release. We …

[v1.6] Fixes for generating data.json

---

cluster/defaults.go
cluster/network.go
types/rke_types.go

- cherry-pick ACI changes from https://github.com/rancher/rke/pull/3678, CI is currently failing because it needs a rebase and updated `data.json`
- `go generate` for adding calico/canal v3.27.4 and v3.28.1 https://github.com/rancher/kontainer-driver-metadata/pull/1490

[v1.6] updates for august patches

---

.github/workflows/workflow.yaml

- Update branch for `release/v1.7` to `main` in workflow.yaml as `release/v2.10` doesnt exist in rancher/rancher

update branch for v1.7 in workflow.yaml

---

metadata/metadata.go

- the current 1.6.99 dev version is causing the rc rke versions to have 1.27.x k8s version as supported in release notes.
https://github.com/rancher/rke/releases/tag/v1.7.0-rc.5

updated dev version to v1.7.99

---

.github/workflows/workflow.yaml
pki/util.go

There was a bump in the go linter action (golangci-lint) action that defaults configuration verification to true, which unexpectedly caused the release pipeline to fail.
This PR sets the verification to the previous default of false.
Because there's a commit we don't want to release in this cycle, we also have to revert it to get the repo in the same state as the latest RC tag (`v1.6.7-rc.1`).

Revert commit and fix CI for v1.6.7 release

---

.github/workflows/workflow.yaml
pki/util.go

There was a bump in the go linter action (golangci-lint) action that defaults configuration verification to true, which unexpectedly caused the release pipeline to fail.
This PR sets the verification to the previous default of false.
Because there's a commit we don't want to release in this cycle, we also have to revert it to get the repo in the same state as the latest RC tag (`v1.7.3-rc.1`).

Revert commit and fix CI for v1.7.3 release

---

pki/util.go

This reverts commit c6758c134d52697b533809b04ba07b18fa86a665.
Re-applying the original commit after a release.
This was reverted in https://github.com/rancher/rke/pull/3791 to allow fixing a CI issue and otherwise release the same thing as the previous rc that came before the reverted commit.

[release/v1.6] Reapply "fix: fix slice init length (#3695)"

---

pki/util.go

This reverts commit 1c68ad08a9adf5c426e1b61035f9885390342ee9.
Re-applying the original commit after a release.
This was reverted in https://github.com/rancher/rke/pull/3790 to allow fixing a CI issue and otherwise release the same thing as the previous rc that came before the reverted commit.

[release/v1.7] Reapply "fix: fix slice init length (#3785)"

---

go.mod
go.sum

https://github.com/rancher/rke/issues/3820
- in https://github.com/rancher/rke/pull/3821 while un unrc image-spec dependency was bumped to v1.1.1
so downgrading it to 1.1.0.
it is at 1.1.0 version in rancher as well. [ref](https://github.com/rancher/rancher/blob/d7f62116eb48fb060f02a10c8b01164048d9eeda/go.mod#L125)

[release/v1.8] fix go mod dependencies

---

cluster/plan.go
cluster/plan_test.go
util/util.go

This reverts commit 740239cb194146f5957bd041af8c6dc9954ded44. 
v1.29 doesn't support v1.31 so this change is not required. Issue: https://github.com/rancher/rancher/issues/49374

[v1.6] Revert "use sha256 for checksumming when k8s version >= 1.31.6"

---

.github/workflows/test-cni.yaml

Currently, the workflow test-cni is triggered to run on the PR that contains only no-code changes, such as on https://github.com/rancher/rke/pull/3835  ( see screenshot below). 
This PR adds the same paths-ignore to the test-cni workflow as the one in the [main workflow](https://github.com/rancher/rke/blob/release/v1.8/.github/workflows/workflow.yaml#L17-L21).
Note that it does not alter the rule that a set of workflows is required for a PR to be merged.

[1.8] Add the same paths-ignore to the test-cni workflow as the one in the main workflow

---

scripts/create-imageslist.sh
scripts/package

Artifacts under build/bin are already uploaded as artifacts: https://github.com/rancher/rke/blob/release/v1.8/.github/workflows/workflow.yaml#L109
https://github.com/rancher/rke/blob/release/v1.8/.github/workflows/workflow.yaml#L130
Creating new file rke-extended-life-images.txt to avoid uploading it manually. See https://github.com/rancher/rke/releases/download/v1.8.7/rke-extended-life-images.txt for reference.

[v1.8] upload rke extended images list on tag
